---
title: "PeakC Interactions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup 

```{r}
"%&%" <- function(a,b) paste0(a,b)
library("data.table")
library("tidyverse")
library("GenomicRanges")
local.dir <- "/Users/jasont/science/projects/wtsa/promoter_driven/"
rescomp.dir <- "/Users/jasont/science/servers/FUSE5/"
work.dir <- rescomp.dir %&% "projects/wtsa/promoter_driven/"
output.dir <- work.dir %&% "peakC_interactions/"
plot.dir <- output.dir %&% "peakC_plots/"
```

Capture Compare output files 

```{r}
# promoter capture files 
prom.cc.file  <- work.dir %&% "03_CaptureCompare/capture-compare-input_hg38.txt"
prom.cc.dir  <- work.dir %&% "03_CaptureCompare/T2D_Promoter_cis_analysis/"
```

peakC: a flexible, non-parametric peak calling package for 4C and Capture-C data

```{r}
library("peakC")
```


# Functions

```{r}

write_unionbg_to_wigfiles <- function(bg.df,chromo,out.dir=local.dir%&%"temp/"){
  samp.vec <- names(bg.df)[4:length(names(bg.df))]
  for (samp in samp.vec){
    sub.df <- filter(bg.df,chrom==chromo)
    sub.df <- dplyr::select(sub.df,one_of("start",samp)) 
    write.table(x=sub.df,file=out.dir%&%samp%&%".wig",sep="\t",quote=F,row.names = F,col.names = F)
  }
}

consolidate_peaks <- function(bg.df,peak.vec){
  # Returns a data frame of contiguous fragments of sig interactions 
  # and a second data frame with a extention of 1Kb to merge proximal interaction 
  sub.df <- filter(bg.df,start%in%peak.vec)
  sub.df$start.expand1K <- sub.df$start - 1000
  sub.df$end.expand1K <- sub.df$end + 1000
  sub.gr <- GRanges(seqnames=sub.df$chrom,IRanges(start=sub.df$start,end=sub.df$end))
  sub.expand.gr <- GRanges(seqnames=sub.df$chrom,IRanges(start=sub.df$start.expand1K,end=sub.df$end.expand1K))
  red.gr <- reduce(sub.gr);red.expand.gr <- reduce(sub.expand.gr)
  out.df1 <- as.data.frame(red.gr); out.df2 <- as.data.frame(red.expand.gr)
  return(list(out.df1,out.df2))
}

build_interaction_df <- function(experiment.name,experiment.dir,capture,
                                  vp,chromo,range=2.5e+05,celltype="Endo"){
  # celltype is a pattern string that is checked in the union bedgraph file used for extraction
  bg.file <- experiment.dir %&% "2_unionBedgraphs/A_raw_counts/" %&% capture %&% "_raw.unionbdg"
  bg.df <- fread(bg.file)  
  if (dim(bg.df)[1]>=1000){ # Capture must contain at least 1000 fragments in unionbedgraph 
    write_unionbg_to_wigfiles(bg.df,chromo)
    file.names <- names(bg.df)[grepl(celltype,names(bg.df))] %&% ".wig"
    file.vec <- local.dir%&%"temp/" %&% file.names 
    data <- readMultiple(file.vec, vp.pos=vp, window = range) # specified range 
    res <- combined.analysis(data=data,num.exp=3,vp.pos=vp,wSize=5,alphaFDR=0.05)
    plot.name <- plot.dir %&% experiment.name %&% "_" %&% capture %&% 
      "_" %&% celltype %&% "_range-" %&% (range/1000) %&% "kb.png"
    ##png(filename = plot.name) # Must run in R not RStudio 
    ##plot_C(res) # Must run in R not RStudio
    ##dev.off() # Must run in R not RStudio
    results.df <- data.frame(start=res$dbR$frag_pos,p.value=res$p.value,
                             ratio=res$ratio,stringsAsFactors = F)
    results.df <- dplyr::inner_join(bg.df,results.df,by="start") %>% 
      dplyr::select(one_of("chrom","start","end","p.value","ratio"))
    results.df$start <- results.df$start %>% as.integer(.)
    peak.vec <- as.integer(res$peak)
    if (length(peak.vec)>0){
      df <- res$dbR 
      df <- df[df$frag_pos %in% peak.vec,]
      pval.vec <- res$p.value[as.integer(row.names(df))]
      ratio.vec <- res$ratio[as.integer(row.names(df))]
      out.df <- filter(bg.df,start%in%peak.vec,chrom==chromo)
      ##out.df <- out.df[!duplicated(out.df$start),]
      out.df$width <- out.df$end - out.df$start
      out.df$p.value <- pval.vec; out.df$ratio <- ratio.vec
      out.df$experiment <- experiment.name; out.df$celltype <- celltype; out.df$capture <- capture
      out.df <- dplyr::select(out.df,one_of("experiment","celltype",
                                            "capture","chrom","start","end",
                                            "width","p.value","ratio"))
      return(list(results.df,out.df))   
    } else{
      return(list(results.df,NULL))
    }    
  } else{
    print("FAILED CAPTURE: " %&% capture)
    return(NULL)
  }
}

```


```{r}

extract_distal <- function(vp,dist.df,limit=2.5e+05){
  dist.df$distal <- map(1:dim(dist.df)[1],function(i){
    v <- c(dist.df[i,]$start,dist.df[i,]$end)
    min(abs(v - vp)) > limit
  }) %>% as.logical(.)
  out.df <- filter(dist.df,distal==TRUE) %>% dplyr::select(.,-one_of("distal"))
  if (dim(out.df)[1]>0){
    return(out.df)    
  } else{
    return(NULL)
  }
}


build_experiment_interaction_df <- function(experiment.name="promoter",experiment.dir=prom.cc.dir,
                                             experiment.file=prom.cc.file,celltype="Endo"){
  ex.df <- read.table(experiment.file,header=F) #fread(experiment.file)
  out.df <- c()
  full.df <- c() 
  pb <- txtProgressBar(min=0,max=dim(ex.df)[1],style=3)
  for (i in 1:dim(ex.df)[1]){
    print(i)
    capture <- ex.df$V1[i]
    chromo <- ex.df$V2[i]
    vp <- ex.df$V3[i]
    build.prox.list <- build_interaction_df(experiment.name,experiment.dir,
                                        capture,vp,chromo,range=2.5e+05,celltype)
    build.dist.list <- build_interaction_df(experiment.name,experiment.dir,
                                        capture,vp,chromo,range=1e+06,celltype)
    if (!is.null(build.dist.list[[2]])){
      check <- extract_distal(vp,build.dist.list[[2]])
      if (is.null(check)){
        build.dist <- NULL
      } else{
        build.dist <- check
      }      
    }
    if (!is.null(build.prox.list[[2]])){
      build.prox <- build.prox.list[[2]]
      build.prox$type <- "proximal"
      out.df <- rbind(out.df,build.prox)
    }
    if (!is.null(build.dist)){
      build.dist$type <- "distal"
      out.df <- rbind(out.df,build.dist)
    }
    build.full.dfa <- build.prox.list[[1]]
    build.full.dfb <- filter(build.dist.list[[1]],
                             !(start %in% build.full.dfa$start))
    build.full.df <- rbind(build.full.dfa,build.full.dfb)
    full.df <- rbind(full.df,build.full.df)
    setTxtProgressBar(pb,i)
  }
  return(list(full.df,out.df))
}

get_dist_from_vp <- function(int.df,experiment.file){
  ex.df <- read.table(experiment.file,header=F) #fread(experiment.file)
  pb <- txtProgressBar(min=0,max=dim(int.df)[1],style=3)
  dist.from.vp <- map(1:dim(int.df)[1],function(i){
    setTxtProgressBar(pb,i)
    row.df <- int.df[i,]
    vp <- filter(ex.df,V1==row.df$capture)$V3 %>% as.integer(.)
    v <- c(row.df$start,row.df$end)
    val <- min(abs(v - vp))  
    sign.val <- unique(sign(v-vp))
    if (length(sign.val)==1){
      unique(sign(v-vp)) * val
    } else{
      c(v-vp)[grepl(v-vp,pattern=val)]
    }
  }) %>% as.integer(.)
  int.df$dist.from.vp <- dist.from.vp
  return(int.df)
}

```

NOTE: Best to run the following code in a regular R script (okay to run above in RMarkdown) but for some reason cannot write png / pdf using png() or pdf() function from WITHIN RMarkdonw file 

# Promoter Capture 

```{r}
prom.list <- build_experiment_interaction_df(experiment.name="promoter",
  experiment.dir=prom.cc.dir,                                 
  experiment.file=prom.cc.file,celltype="Endo")
prom.df <- prom.list[[2]] %>% get_dist_from_vp(.,experiment.file=prom.cc.file)
write.table(x=prom.df,file=output.dir%&%"promoter_endo_peakC-interactions.txt",
            sep="\t",quote=F,row.names=F)
write.table(x=prom.list[[1]],file=output.dir%&%"promoter_endo_peakC-output.txt",
            sep="\t",quote=F,row.names=F)
```
