---
title: "04.2.2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup 

```{r}
"%&%" <- function(a,b) paste0(a,b)
library("data.table")
library("tidyverse")
library("GenomicRanges")
rescomp.dir <- "/Users/jasont/science/servers/FUSE5/"
work.dir <- rescomp.dir %&% 
  "projects/wtsa/promoter_driven/"
input.dir <- work.dir %&% "peakC_interactions/"
output.dir <- work.dir %&% "peakC_interactions/track_files/"
```

```{r}
prom.df <- fread(input.dir %&% "promoter_endo_peakC-interactions.txt")
prom.full.df <- fread(input.dir %&% "promoter_endo_peakC-output.txt")
```

Note: For visualization purposes, need to remove duplicate fragments to generate bigwig files 
```{r}
create_track_dfs <- function(peak.df,full.df){
  bed.df <- dplyr::select(peak.df,one_of("chrom","start","end","capture"))
  nlp.df <- dplyr::select(full.df,one_of("chrom","start","end"))
  nlp.df$nlp <- -1*log(full.df$p.value,base=10)
  nlp.df <- nlp.df[!duplicated(nlp.df$start),]
  ratio.df <- dplyr::select(full.df,one_of("chrom","start","end","ratio"))
  ratio.df <- ratio.df[!duplicated(ratio.df$start),]
  out.list <- list(bed.df,nlp.df,ratio.df)
  return(out.list)
}
```

## Promoter files 
```{r}
prom.list <- create_track_dfs(prom.df,prom.full.df)
write.table(x=prom.list[[1]],file=output.dir %&% 
              "promoter_endo_peakC-interactions.bed",sep="\t",row.names=F,
            col.names=F,quote=F)
write.table(x=prom.list[[2]],file=output.dir %&% 
              "promoter_endo_peakC-interactions_nlp.bedGraph",sep="\t",row.names=F,
            col.names=F,quote=F)
write.table(x=prom.list[[3]],file=output.dir %&% 
              "promoter_endo_peakC-interactions_ratio.bedGraph",sep="\t",row.names=F,
            col.names=F,quote=F)
```


## Create big bed files with these commands on the command line:
./bedToBigBed bedExample.txt hg38.chrom.sizes myBigBed.bb

```{bash}
sort -k1,1 -k2,2n promoter_endo_peakC-interactions.bed > promoter_endo_peakC-interactions.sorted.bed 
./bedToBigBed promoter_endo_peakC-interactions.sorted.bed hg38.chrom.sizes promoter_endo_peakC-interactions.bb
```

## Create bigWig files by converting from the bedGraph files  
./bedGraphToBigWig in.bedGraph chrom.sizes myBigWig.bw

```{bash}
sort -k1,1 -k2,2n promoter_endo_peakC-interactions_nlp.bedGraph > promoter_endo_peakC-interactions_nlp.sorted.bedGraph 
./bedGraphToBigWig promoter_endo_peakC-interactions_nlp.sorted.bedGraph hg38.chrom.sizes promoter_endo_peakC-interactions_nlp.bw

sort -k1,1 -k2,2n promoter_endo_peakC-interactions_ratio.bedGraph > promoter_endo_peakC-interactions_ratio.sorted.bedGraph 
./bedGraphToBigWig promoter_endo_peakC-interactions_ratio.sorted.bedGraph hg38.chrom.sizes promoter_endo_peakC-interactions_ratio.bw
```

