---
title: "DESeq2-interactions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup 

# Setup 

```{r}
"%&%" <- function(a,b) paste0(a,b)
library("data.table")
library("tidyverse")
library("GenomicRanges")
#if (!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
#BiocManager::install("DESeq2")
library("DESeq2")
local.dir <- "/Users/jasont/science/projects/wtsa/promoter_driven/"
rescomp.dir <- "/Users/jasont/science/servers/FUSE5/"
work.dir <- rescomp.dir %&% "projects/wtsa/promoter_driven/"
output.dir <- work.dir %&% "DESeq2_interactions/"
```


Capture Compare output files 

```{r}
# promoter capture files 
prom.cc.file  <- work.dir %&% "03_CaptureCompare/capture-compare-input_hg38.txt"
prom.cc.dir  <- work.dir %&% "03_CaptureCompare/T2D_Promoter_cis_analysis/"
```


```{r}

##consolidate_peaks <- function(bg.df,chrom,peak.vec){
##  # Returns a data frame of contiguous fragments of sig interactions 
##  # and a second data frame with a extention of 1Kb to merge proximal interaction 
##  sub.df <- filter(bg.df,chrom==chrom,start%in%peak.vec)
##  sub.df$start.expand1K <- sub.df$start - 1000
##  sub.df$end.expand1K <- sub.df$end + 1000
##  sub.gr <- GRanges(seqnames=sub.df$chrom,IRanges(start=sub.df$start,end=sub.df$end))
##  sub.expand.gr <- GRanges(seqnames=sub.df$chrom,IRanges(start=sub.df$start.expand1K,end=sub.df$end.expand1K))
##  red.gr <- reduce(sub.gr);red.expand.gr <- reduce(sub.expand.gr)
##  out.df1 <- as.data.frame(red.gr); out.df2 <- as.data.frame(red.expand.gr)
##  return(list(out.df1,out.df2))
##}

run_deseq2 <- function(bg.df,vp,chrom,celltype1="Endo",celltype2="LCL"){
  # celltype 1 and 2 are patterns indicating main and reference cell types 
  sub.df <- bg.df 
  sub.bkup <- filter(bg.df,chrom==chrom,start>=(vp-1e6),end<=(vp+1e6))
  frag.vec <- sub.df$chrom %&% ":" %&% sub.df$start %&% "-" %&% sub.df$end
  a.df <- dplyr::select(sub.df,contains(celltype1))
  b.df <- dplyr::select(sub.df,contains(celltype2))
  data.mat <- cbind(a.df,b.df) %>% as.matrix(.)
  row.names(data.mat)<-frag.vec
  # phenotype data frame 
  celltype <- c(rep(celltype1,dim(a.df)[2]),rep(celltype2,dim(b.df)[2]))
  pheno.df <- as.data.frame(celltype)
  pheno.df$celltype <- as.factor(pheno.df$celltype)
  row.names(pheno.df) <- c(names(a.df),names(b.df))
  ddsFullCountTable <- DESeqDataSetFromMatrix(
    countData = data.mat,
    colData = pheno.df,
    design = ~ celltype )
  res.df <- tryCatch(
    {
      dds <- suppressMessages(DESeq(ddsFullCountTable))
      res <- results(dds, contrast = c("celltype",celltype1,celltype2))
      as.data.frame(res)
    },
    error=function(cond) {
      message("\nDESeq2 yielded error")
      message("Here's the original error message:")
      message(cond)
      return(NA)
    },
    finally={
      message("")
    }
  )
  if (length(res.df)<2){ # Will be the case for NA as lenght is one, to prevent warning message 
    if (is.na(res.df)){
      frag.vec <- sub.bkup$chrom %&% ":" %&% sub.bkup$start %&% "-" %&% sub.bkup$end
      a.df <- dplyr::select(sub.bkup,contains(celltype1))
      b.df <- dplyr::select(sub.bkup,contains(celltype2))
      data.mat <- cbind(a.df,b.df) %>% as.matrix(.)
      row.names(data.mat)<-frag.vec
      # phenotype data frame 
      celltype <- c(rep(celltype1,dim(a.df)[2]),rep(celltype2,dim(b.df)[2]))
      pheno.df <- as.data.frame(celltype)
      pheno.df$celltype <- as.factor(pheno.df$celltype)
      row.names(pheno.df) <- c(names(a.df),names(b.df))
      ddsFullCountTable <- DESeqDataSetFromMatrix(
        countData = data.mat,
        colData = pheno.df,
        design = ~ celltype )  
      dds <- suppressMessages(DESeq(ddsFullCountTable))
      res <- results(dds, contrast = c("celltype",celltype1,celltype2))
      res.df <- as.data.frame(res)
    }    
  }
  return(res.df)
}

build_interaction_dfs <- function(experiment.name,experiment.dir,capture,
                                  chrom,vp,celltype1="Endo",celltype2="LCL"){
  # celltype is a pattern string that is checked in the union bedgraph file used for extraction
  bg.file <- experiment.dir %&% "2_unionBedgraphs/A_raw_counts/" %&% capture %&% "_raw.unionbdg"
  bg.df <- fread(bg.file)  
  #bg.df$chrom <- as.factor(bg.df$chrom)
  if (dim(bg.df)[1]>=1000){ # Capture must contain at least 1000 fragments in unionbedgraph 
    res.df <- run_deseq2(bg.df,vp,chrom,celltype1,celltype2)
    res.df$fragment <- row.names(res.df)
    res.df$seqnames <- purrr::map(res.df$fragment,function(s){
      strsplit(x=s,split=":")[[1]][1]
    }) %>% as.character(.)
    res.df$start <- purrr::map(res.df$fragment,function(s){
      (strsplit(x=s,split=":")[[1]][2] %>% strsplit(.,split="-"))[[1]][1]
    }) %>% as.integer(.)
    res.df$end <- purrr::map(res.df$fragment,function(s){
      (strsplit(x=s,split=":")[[1]][2] %>% strsplit(.,split="-"))[[1]][2]
    }) %>% as.integer(.)
    res.df$capture<-capture
    peak.df <- filter(na.omit(res.df),padj<0.05) # FDR 5% 
    peak.df <- filter(peak.df,sign(stat)>0) # retain interactions that are higher in Endos 
    if (dim(peak.df)[1]>0){
      out.df <- peak.df
      out.df$width <- out.df$end - out.df$start
      out.df$experiment <- experiment.name; out.df$celltype1 <- celltype1; 
      out.df$celltype2 <- celltype2; out.df$capture <- capture
      out.df <- dplyr::select(out.df,
        one_of("experiment","celltype1","celltype2","capture","seqnames",
               "start","end","width","baseMean","log2FoldChange","lfcSE","stat",
               "pvalue","padj"))
      return(list(res.df,out.df))    
    } else{
      return(list(res.df,NULL))
    }    
  } else{
    print("FAILED CAPTURE: " %&% capture)
    return(NULL)
  }
}

```



```{r}

build_experiment_interaction_dfs <- function(experiment.name="promoter",experiment.dir=prom.cc.dir,
                                             experiment.file=prom.cc.file,
                                             celltype1="Endo",celltype2="LCL"){
  ex.df <- read.table(experiment.file,header=F) #fread(experiment.file)
  out.df <- c()
  full.df <- c() 
  pb <- txtProgressBar(min=0,max=dim(ex.df)[1],style=3)
  for (i in 1:dim(ex.df)[1]){
    print(i)
    capture <- ex.df$V1[i]
    chrom <- ex.df$V2[i]
    vp <- ex.df$V3[i]
    build.list <- build_interaction_dfs(experiment.name,experiment.dir,capture,
                                        chrom,vp,celltype1,celltype2)
    if (!is.null(build.list)){
      full.df <- rbind(full.df,build.list[[1]])
      if (!is.null(build.list[[2]])){
        out.df <- rbind(out.df,build.list[[2]])
      }
    }
    setTxtProgressBar(pb,i)
  }
  return(list(full.df,out.df))
}

get_dist_from_vp <- function(int.df,experiment.file){
  ex.df <- read.table(experiment.file,header=F) #fread(experiment.file)
  pb <- txtProgressBar(min=0,max=dim(int.df)[1],style=3)
  dist.from.vp <- map(1:dim(int.df)[1],function(i){
    setTxtProgressBar(pb,i)
    row.df <- int.df[i,]
    vp <- filter(ex.df,V1==row.df$capture)$V3 %>% as.integer(.)
    v <- c(row.df$start,row.df$end)
    val <- min(abs(v - vp))    
    sign.val <- unique(sign(v-vp))
    if (length(sign.val)==1){
      unique(sign(v-vp)) * val
    } else{
      c(v-vp)[abs(v-vp)==min(abs(v-vp))]#[grepl(v-vp,pattern=val)]
    }
  }) %>% as.integer(.)
  int.df$dist.from.vp <- dist.from.vp
  return(int.df)
}

```


# Promoter Capture 

```{r}
prom.list <- build_experiment_interaction_dfs(experiment.name="promoter",
                                              experiment.dir=prom.cc.dir,
                                             experiment.file=prom.cc.file,
                                             celltype1="Endo",celltype2="LCL")
prom.df <- prom.list[[2]] %>% get_dist_from_vp(.,experiment.file=prom.cc.file)
prom.df$type <- ifelse(prom.df$dist.from.vp <= 2.5e+05,"proximal","distal")
write.table(x=prom.df,file=output.dir%&%"promoter_endo_DESeq2-interactions_rerun.txt",
            sep="\t",quote=F,row.names=F)
write.table(x=prom.list[[1]],file=output.dir%&%"promoter_endo_DESeq2-output_rerun.txt",
            sep="\t",quote=F,row.names=F)
```
