---
title: "04.3.2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup 

```{r}
"%&%" <- function(a,b) paste0(a,b)
library("data.table")
library("tidyverse")
rescomp.dir <- "/Users/jasont/science/servers/FUSE5/"
work.dir <- rescomp.dir %&% 
  "projects/wtsa/promoter_driven/"
input.dir <- work.dir %&% "DESeq2_interactions/"
output.dir <- work.dir %&% "DESeq2_interactions/track_files/"
```


```{r}
prom.df <- fread(input.dir %&% "promoter_endo_DESeq2-interactions.txt")
prom.full.df <- fread(input.dir %&% "promoter_endo_DESeq2-output.txt")
```

Note: For visualization purposes, need to remove duplicate fragments to generate bigwig files 
```{r}
create_track_dfs <- function(peak.df,full.df){
  # baseMean	log2FoldChange	lfcSE	stat	pvalue	padj
  bed.df <- dplyr::select(peak.df,one_of("seqnames","start","end","capture"))
  bm.df <- dplyr::select(full.df,one_of("seqnames","start","end","baseMean"))
  bm.df <- bm.df[!duplicated(bm.df$start),]
  l2fc.df <- dplyr::select(full.df,one_of("seqnames","start","end","log2FoldChange"))
  l2fc.df <- l2fc.df[!duplicated(l2fc.df$start),]
  lfcSE.df <- dplyr::select(full.df,one_of("seqnames","start","end","lfcSE"))
  lfcSE.df <- lfcSE.df[!duplicated(lfcSE.df$start),]
  stat.df <- dplyr::select(full.df,one_of("seqnames","start","end","stat"))
  stat.df <- stat.df[!duplicated(stat.df$start),]
  pval.df <- dplyr::select(full.df,one_of("seqnames","start","end","pvalue"))
  pval.df <- pval.df[!duplicated(pval.df$start),]
  padj.df <- dplyr::select(full.df,one_of("seqnames","start","end","padj"))
  padj.df <- padj.df[!duplicated(padj.df$start),]
  padj.df <- na.omit(padj.df)
  out.list <- list(bed.df,bm.df,l2fc.df,lfcSE.df,stat.df,pval.df,padj.df)
  return(out.list)
}
```

## Promoter files 
```{r}
prom.list <- create_track_dfs(prom.df,prom.full.df)
write.table(x=prom.list[[1]],file=output.dir %&% 
              "promoter_endo_DESeq2-interactions.bed",sep="\t",row.names=F,
            col.names=F,quote=F)
write.table(x=prom.list[[2]],file=output.dir %&% 
              "promoter_endo_DESeq2-interactions_bm.bedGraph",sep="\t",row.names=F,
            col.names=F,quote=F)
write.table(x=prom.list[[3]],file=output.dir %&% 
              "promoter_endo_DESeq2-interactions_l2fc.bedGraph",sep="\t",row.names=F,
            col.names=F,quote=F)
write.table(x=prom.list[[4]],file=output.dir %&% 
              "promoter_endo_DESeq2-interactions_lfcSE.bedGraph",sep="\t",row.names=F,
            col.names=F,quote=F)
write.table(x=prom.list[[5]],file=output.dir %&% 
              "promoter_endo_DESeq2-interactions_stat.bedGraph",sep="\t",row.names=F,
            col.names=F,quote=F)
write.table(x=prom.list[[6]],file=output.dir %&% 
              "promoter_endo_DESeq2-interactions_pval.bedGraph",sep="\t",row.names=F,
            col.names=F,quote=F)
write.table(x=prom.list[[7]],file=output.dir %&% 
              "promoter_endo_DESeq2-interactions_padj.bedGraph",sep="\t",row.names=F,
            col.names=F,quote=F)
```

## Create big bed files with these commands on the command line:
./bedToBigBed bedExample.txt hg38.chrom.sizes myBigBed.bb

```{bash}
sort -k1,1 -k2,2n promoter_endo_DESeq2-interactions.bed > promoter_endo_DESeq2-interactions.sorted.bed
./bedToBigBed promoter_endo_DESeq2-interactions.sorted.bed hg38.chrom.sizes promoter_endo_DESeq2-interactions.bb
```

## Create bigWig files by converting from the bedGraph files  
./bedGraphToBigWig in.bedGraph chrom.sizes myBigWig.bw
 
```{bash}
sort -k1,1 -k2,2n promoter_endo_DESeq2-interactions_bm.bedGraph > promoter_endo_DESeq2-interactions_bm.sorted.bedGraph 
./bedGraphToBigWig promoter_endo_DESeq2-interactions_bm.sorted.bedGraph hg38.chrom.sizes promoter_endo_DESeq2-interactions_bm.bw

sort -k1,1 -k2,2n promoter_endo_DESeq2-interactions_l2fc.bedGraph > promoter_endo_DESeq2-interactions_l2fc.sorted.bedGraph 
./bedGraphToBigWig promoter_endo_DESeq2-interactions_l2fc.sorted.bedGraph hg38.chrom.sizes promoter_endo_DESeq2-interactions_l2fc.bw

sort -k1,1 -k2,2n promoter_endo_DESeq2-interactions_lfcSE.bedGraph > promoter_endo_DESeq2-interactions_lfcSE.sorted.bedGraph 
./bedGraphToBigWig promoter_endo_DESeq2-interactions_lfcSE.sorted.bedGraph hg38.chrom.sizes promoter_endo_DESeq2-interactions_lfcSE.bw

sort -k1,1 -k2,2n promoter_endo_DESeq2-interactions_stat.bedGraph > promoter_endo_DESeq2-interactions_stat.sorted.bedGraph 
./bedGraphToBigWig promoter_endo_DESeq2-interactions_stat.sorted.bedGraph hg38.chrom.sizes promoter_endo_DESeq2-interactions_stat.bw

sort -k1,1 -k2,2n promoter_endo_DESeq2-interactions_pval.bedGraph > promoter_endo_DESeq2-interactions_pval.sorted.bedGraph 
./bedGraphToBigWig promoter_endo_DESeq2-interactions_pval.sorted.bedGraph hg38.chrom.sizes promoter_endo_DESeq2-interactions_pval.bw

sort -k1,1 -k2,2n promoter_endo_DESeq2-interactions_padj.bedGraph > promoter_endo_DESeq2-interactions_padj.sorted.bedGraph 
./bedGraphToBigWig promoter_endo_DESeq2-interactions_padj.sorted.bedGraph hg38.chrom.sizes promoter_endo_DESeq2-interactions_padj.bw
```
