---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup 

# Setup 

```{r}

"%&%" <- function(a,b) paste0(a,b)
library("data.table")
library("tidyverse")
library("GenomicRanges")
library("DESeq2")

local.dir <- "/home/jason/science/projects/wtsa/joint_analyses/"
rescomp.dir <- "/home/jason/science/servers/FUSE5/"
cbrg.dir <- "/home/jason/science/servers/FUSE2/"
output.dir <- rescomp.dir %&% "projects/wtsa/joint_analyses/DESeq2_interactions/"

```


Capture Compare output files 

```{r}

# promoter capture files 
prom.dir <- cbrg.dir %&% "wtsa/promoter_driven/"
prom.cc.file  <- prom.dir %&% "capture_compare_parameters.txt"
prom.cc.dir  <- prom.dir %&% "PromCap_cis_analysis/"
# enhancer capture first round  
e1.dir <- cbrg.dir %&% "wtsa/enhancer_driven/first_round/"
e1.cc.file  <- e1.dir %&% "capture_compare_parameters_pruned_chr.txt"
e1.cc.dir  <- e1.dir %&% "capture_compare_cis_analysis/"
# enhancer capture second round  
e2.dir <- cbrg.dir %&% "wtsa/enhancer_driven/second_round/"
e2.cc.file  <- e2.dir %&% "capture_compare_parameters_pruned_chr.txt"
e2.cc.dir  <- e2.dir %&% "troubleshoot_cis_analysis/"

```


```{r}


consolidate_peaks <- function(bg.df,chrom,peak.vec){
  # Returns a data frame of contiguous fragments of sig interactions 
  # and a second data frame with a extention of 1Kb to merge proximal interaction 
  sub.df <- filter(bg.df,chrom==chrom,start%in%peak.vec)
  sub.df$start.expand1K <- sub.df$start - 1000
  sub.df$end.expand1K <- sub.df$end + 1000
  sub.gr <- GRanges(seqnames=sub.df$chrom,IRanges(start=sub.df$start,end=sub.df$end))
  sub.expand.gr <- GRanges(seqnames=sub.df$chrom,IRanges(start=sub.df$start.expand1K,end=sub.df$end.expand1K))
  red.gr <- reduce(sub.gr);red.expand.gr <- reduce(sub.expand.gr)
  out.df1 <- as.data.frame(red.gr); out.df2 <- as.data.frame(red.expand.gr)
  return(list(out.df1,out.df2))
}

run_deseq2 <- function(bg.df,vp,chrom,range,celltype1="Endo",celltype2="Blymph"){
  # celltype 1 and 2 are patterns indicating main and reference cell types 
  sub.df <- filter(bg.df,chrom==chrom,start>=(vp-range),end<=(vp+range))
  frag.vec <- sub.df$chrom %&% ":" %&% sub.df$start %&% "-" %&% sub.df$end
  a.df <- dplyr::select(sub.df,contains(celltype1))
  b.df <- dplyr::select(sub.df,contains(celltype2))
  data.mat <- cbind(a.df,b.df) %>% as.matrix(.)
  row.names(data.mat)<-frag.vec
  # phenotype data frame 
  celltype <- c(rep(celltype1,dim(a.df)[2]),rep(celltype2,dim(b.df)[2]))
  pheno.df <- as.data.frame(celltype)
  row.names(pheno.df) <- c(names(a.df),names(b.df))
  ddsFullCountTable <- DESeqDataSetFromMatrix(
    countData = data.mat,
    colData = pheno.df,
    design = ~ celltype )
  dds <- suppressMessages(DESeq(ddsFullCountTable))
  res <- results(dds, contrast = c("celltype",celltype1,celltype2))
  res.df <- as.data.frame(res)
  return(res.df)
}

build_interaction_dfs <- function(experiment.name,experiment.dir,capture,
                                  chrom,vp,celltype1="Endo",celltype2="Blymph",range=5e+05){
  # celltype is a pattern string that is checked in the union bedgraph file used for extraction
  bg.file <- experiment.dir %&% "2_unionBedgraphs/A_raw_counts/" %&% capture %&% "_raw.unionbdg"
  bg.df <- fread(bg.file)  
  if (dim(bg.df)[1]>=1000){ # Capture must contain at least 1000 fragments in unionbedgraph 
    res.df <- run_deseq2(bg.df,vp,chrom,range,celltype1,celltype2)
    res.df$fragment <- row.names(res.df)
    peak.df <- filter(na.omit(res.df),padj<0.10)
    if (dim(peak.df)[1]>0){
      peak.vec <- map(peak.df$fragment,function(s){
        (strsplit(s,split=":")[[1]][2] %>% strsplit(.,split="-"))[[1]][1]}) %>% as.integer(.)
      out.list <- consolidate_peaks(bg.df,chrom,peak.vec)
      out.df1 <- out.list[[1]]; out.df2 <- out.list[[2]]
      out.df1$experiment <- experiment.name; out.df1$celltype1 <- celltype1; 
      out.df1$celltype2 <- celltype2; out.df1$capture <- capture
      out.df2$experiment <- experiment.name; out.df2$celltype1 <- celltype1; 
      out.df2$celltype2 <- celltype2; out.df2$capture <- capture
      out.df1 <- dplyr::select(out.df1,one_of("experiment","celltype1","celltype2",
                                              "capture","seqnames","start","end","width"))
      out.df2 <- dplyr::select(out.df2,one_of("experiment","celltype1","celltype2",
                                              "capture","seqnames","start","end","width"))
      return(list(out.df1,out.df2))    
    } else{
      return(NULL)
    }    
  } else{
    print("FAILED CAPTURE: " %&% capture)
    return(NULL)
  }
}


```



```{r}


build_experiment_interaction_dfs <- function(experiment.name="promoter",experiment.dir=prom.cc.dir,
                                             experiment.file=prom.cc.file,
                                             celltype1="Endo",celltype2="Blymph"){
  ex.df <- fread(experiment.file)
  out.df1 <- c()
  out.df2 <- c()
  pb <- txtProgressBar(min=0,max=dim(ex.df)[1],style=3)
  for (i in 1:dim(ex.df)[1]){
    #print(i)
    capture <- ex.df$V1[i]
    chrom <- ex.df$V2[i]
    vp <- ex.df$V3[i]
    build.list <- build_interaction_dfs(experiment.name,experiment.dir,capture,
                                        chrom,vp,celltype1,celltype2,range=3e+05)
    if (!is.null(build.list)){
      out.df1 <- rbind(out.df1,build.list[[1]]); out.df2 <- rbind(out.df2,build.list[[2]]); 
    }
    setTxtProgressBar(pb,i)
  }
  return(list(out.df1,out.df2))
}

get_dist_from_vp <- function(int.df,experiment.file){
  ex.df <- fread(experiment.file)
  pb <- txtProgressBar(min=0,max=dim(int.df)[1],style=3)
  dist.from.vp <- map(1:dim(int.df)[1],function(i){
    setTxtProgressBar(pb,i)
    row.df <- int.df[i,]
    vp <- filter(ex.df,V1==row.df$capture)$V3
    v <- c(row.df$start,row.df$end)
    min(abs(v - vp))    
  }) %>% as.integer(.)
  int.df$dist.from.vp <- dist.from.vp
  return(int.df)
}

```


# Promoter Capture 

```{r}

prom.list <- build_experiment_interaction_dfs(experiment.name="promoter",experiment.dir=prom.cc.dir,
                                             experiment.file=prom.cc.file,
                                             celltype1="Endo",celltype2="Blymph")
prom.df1 <- prom.list[[1]] %>% get_dist_from_vp(.,experiment.file=prom.cc.file)
prom.df1$type <- ifelse(prom.df1$dist.from.vp <= 2.5e+05,"proximal","distal")
prom.df2 <- prom.list[[2]] %>% get_dist_from_vp(.,experiment.file=prom.cc.file)
prom.df2$type <- ifelse(prom.df2$dist.from.vp <= 2.5e+05,"proximal","distal")
write.table(x=prom.df1,file=output.dir%&%"promoter_endo_DESeq2-interactions.txt",
            sep="\t",quote=F,row.names=F)
write.table(x=prom.df2,file=output.dir%&%"promoter_endo_DESeq2-interactions_merge1K.txt",
            sep="\t",quote=F,row.names=F)

```


# Enhancer Capture (first round)

```{r}

e1.list <- build_experiment_interaction_dfs(experiment.name="enhancer.1st",experiment.dir=e1.cc.dir,
                                             experiment.file=e1.cc.file,
                                            celltype1="Endo",celltype2="hESC")
e1.df1 <- e1.list[[1]] %>% get_dist_from_vp(.,experiment.file=e1.cc.file)
e1.df1$type <- ifelse(e1.df1$dist.from.vp <= 2.5e+05,"proximal","distal")
e1.df2 <- e1.list[[2]] %>% get_dist_from_vp(.,experiment.file=e1.cc.file)
e1.df2$type <- ifelse(e1.df2$dist.from.vp <= 2.5e+05,"proximal","distal")
write.table(x=e1.df1,file=output.dir%&%"enhancer-firstRound_endo_DESeq2-interactions.txt",
            sep="\t",quote=F,row.names=F)
write.table(x=e1.df2,file=output.dir%&%"enhancer-firstRound_endo_DESeq2-interactions_merge1K.txt",
            sep="\t",quote=F,row.names=F)

```


FAILED CAPTURE: CDC123__86DF__cv__chr10_12307894
FAILED CAPTURE: rs11257658_CAMK1D__5QTL__eQTL__chr10_12309268
FAILED CAPTURE: CDKAL1__50DF__cv__chr6_20673880
FAILED CAPTURE: CDKAL1__50DF__cv__chr6_20686573
FAILED CAPTURE: CDKAL1__50DF__cv__chr6_20688121
FAILED CAPTURE: LINC01512__55DF__cv__chr6_43814625


# Enhancer Capture (second round)

```{r}

e2.list <- build_experiment_interaction_dfs(experiment.name="enhancer.2nd",experiment.dir=e2.cc.dir,
                                             experiment.file=e2.cc.file,
                                            celltype1="Endo",celltype2="hESC")
e2.df1 <- e2.list[[1]] %>% get_dist_from_vp(.,experiment.file=e2.cc.file)
e2.df1$type <- ifelse(e2.df1$dist.from.vp <= 2.5e+05,"proximal","distal")
e2.df2 <- e2.list[[2]] %>% get_dist_from_vp(.,experiment.file=e2.cc.file)
e2.df2$type <- ifelse(e2.df2$dist.from.vp <= 2.5e+05,"proximal","distal")
write.table(x=e2.df1,file=output.dir%&%"enhancer-secondRound_DESeq2_peakC-interactions.txt",
            sep="\t",quote=F,row.names=F)
write.table(x=e2.df2,file=output.dir%&%"enhancer-secondRound_DESeq2_peakC-interactions_merge1K.txt",
            sep="\t",quote=F,row.names=F)

```


