---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup 


```{r}

"%&%" <- function(a,b) paste0(a,b)
library("data.table");library("tidyverse")
work.dir <- "/home/jason/science/projects/wtsa/enhancer_driven/second_round/probe_design/"
fname <- work.dir %&% "FinalListEnhancerCapture2ndRound_2019-01-25.txt"

serv.dir <- "/home/jason/science/servers/FUSE/"
serv.dir2 <- "/home/jason/science/servers/FUSE5/"

dpn.file <- serv.dir %&% "reference/DpnII/hg19_DpnII-sites.bed.gz"

```


```{r}

df <- fread(fname)
df$chrom <- map(df$chr,function(s){
  gsub(x=s,pattern="chr",replace="")
}) %>% as.integer(.)
names(df)[2:3] <- c("bp.start","bp.end")
df <- arrange(df,chr,bp.start)
df$chr[1:2] <- rep("chr10",2)
df$chrom[1:2] <- rep(10,2)
df <- arrange(df,chr,bp.start)
df$bp.start[29] <- 87862954
df$bp.end[29] <- 87863074
df$bp.start[30] <- 87864373
df$bp.end[30] <- 87864493
df <- arrange(df,chr,bp.start)


names(df)[8] <- "ProbeID"
df$frag <- map(df$ProbeID,function(s){
  strsplit(s,split="chr")[[1]][2]
}) %>% as.character(.)

View(select(df,one_of("ProbeID","frag")))

sub.df <- select(df,one_of("ProbeID","Sequence"))
write.table(x=sub.df,file=work.dir%&%"Probes-to-order.txt",sep="\t",quote=F,row.names=F)


df$frag[19:22] <- c("PTEN","PTEN","RNLS","RNLS")

df$probe.type <- map(df$frag,function(f){
  sub <- filter(df,frag==f)
  ifelse(dim(sub)[1]==1,"single","paired")
}) %>% as.character(.)

df$frag[4] <- "1_214150445_PROX1"
df$probe.type[3:4] <- "paired"

View(filter(df,probe.type=="single"))

```



```{r}

dpn.df <- fread("cat " %&% dpn.file %&% " | zcat ")

```



# Append Fragment coordinates for paired and singles 

```{r}

get_frag_start <- function(f){
  sub <- filter(df,frag==f) %>% select(.,one_of("chr","bp.start","bp.end","probe.type"))
  if (unique(sub$probe.type)=="paired"){
    frag.start <- sub$bp.start[1]
  } else {
      sub1 <- filter(dpn.df,V1==sub$chr,V2==(sub$bp.start+1))
      sub2 <- filter(dpn.df,V1==sub$chr,V3==(sub$bp.end-3))
      if (dim(sub1)[1]==1){
        frag.start <- sub1$V2
      } else if (dim(sub2)[1]==1){
        frag.start <- sub2$V2
      } else {
        frag.start <- NA
      }
  }
  return(frag.start)
}

get_frag_end <- function(f){
  sub <- filter(df,frag==f) %>% select(.,one_of("chr","bp.start","bp.end","probe.type"))
  if (unique(sub$probe.type)=="paired"){
    frag.end <- sub$bp.end[2]
  } else {
      sub1 <- filter(dpn.df,V1==sub$chr,V2==(sub$bp.start+1))
      sub2 <- filter(dpn.df,V1==sub$chr,V3==(sub$bp.end-3))
      if (dim(sub1)[1]==1){
        frag.end <- sub1$V3
      } else if (dim(sub2)[1]==1){
        frag.end <- sub2$V3
      } else {
        frag.end <- NA
      }
  }
  return(frag.end)
  
}


frag.start <- c() 
for (f in df$frag){
  val <- get_frag_start(f)
  frag.start <- append(frag.start,val)
}

frag.end <- c() 
for (f in df$frag){
  val <- get_frag_end(f)
  frag.end <- append(frag.end,val)
}

df$frag.start <- frag.start %>% as.integer(.)
df$frag.end <- frag.end %>% as.integer(.)
df$bp.start <- df$bp.start %>% as.integer(.)
df$bp.end <- df$bp.end %>% as.integer(.)


write.table(x=df,file=work.dir%&%"probe-file-expanded-info.txt",sep="\t",row.names=F,quote=F)

```


```{r}

sub.df <- select(df,one_of("chr","frag.start","frag.end","frag","probe.type"))
# 218 probes 
filter(sub.df,probe.type=="single") %>% dim(.)
# 38 of these are single probes 
(218-38)/2
# there are 90 pairs of probes 

sub.df <- sub.df[!duplicated(sub.df),]
# There are 128 captures (i.e. at unique DpnII fragments) to be completed 
table(sub.df$probe.type)
# 90 paired captures and 38 single captures 



```


# Check to see which SNPs are covered by probed fragments 


```{r}

library("GenomicRanges")

snp.dir <- serv.dir2 %&% "projects/wtsa/enhancer_driven/second_round/probe_design/"
t2d.full <- fread(snp.dir %&% "second-round_T2D-SNPs_PPA10_withFirstRound.txt")
t2d.sub <- fread(snp.dir %&% "second-round_T2D-SNPs_PPA10.txt")
eng.full <- fread(snp.dir %&% "second-round_ENGAGE-SNPs_PPA10_withFirstRound.txt")
eng.sub <- fread(snp.dir %&% "second-round_ENGAGE-SNPs_PPA10.txt")

```


```{r}

t2d.full$capture <- map(1:(dim(t2d.full)[1]),function(i){
  row.df <- t2d.full[i,]
  sub <- filter(sub.df,chr==row.df$CHR,frag.start<=row.df$POS,frag.end>=row.df$POS)
  ifelse(dim(sub)[1]!=0,TRUE,FALSE)
}) %>% as.logical(.)
t2d.full$probe.type <- map(1:(dim(t2d.full)[1]),function(i){
  row.df <- t2d.full[i,]
  val <- filter(sub.df,chr==row.df$CHR,frag.start<=row.df$POS,frag.end>=row.df$POS)$probe.type
  ifelse(length(val)>0,val,NA)
}) %>% as.character(.)
t2d.sub$capture <- map(1:(dim(t2d.sub)[1]),function(i){
  row.df <- t2d.sub[i,]
  sub <- filter(sub.df,chr==row.df$CHR,frag.start<=row.df$POS,frag.end>=row.df$POS)
  ifelse(dim(sub)[1]!=0,TRUE,FALSE)
}) %>% as.logical(.)
t2d.sub$probe.type <- map(1:(dim(t2d.sub)[1]),function(i){
  row.df <- t2d.sub[i,]
  val <- filter(sub.df,chr==row.df$CHR,frag.start<=row.df$POS,frag.end>=row.df$POS)$probe.type
  ifelse(length(val)>0,val,NA)
}) %>% as.character(.)


eng.full$capture <- map(1:(dim(eng.full)[1]),function(i){
  row.df <- eng.full[i,]
  sub <- filter(sub.df,chr==row.df$CHR,frag.start<=row.df$POS,frag.end>=row.df$POS)
  ifelse(dim(sub)[1]!=0,TRUE,FALSE)
}) %>% as.logical(.)
eng.full$probe.type <- map(1:(dim(eng.full)[1]),function(i){
  row.df <- eng.full[i,]
  val <- filter(sub.df,chr==row.df$CHR,frag.start<=row.df$POS,frag.end>=row.df$POS)$probe.type
  ifelse(length(val)>0,val,NA)
}) %>% as.character(.)
eng.sub$capture <- map(1:(dim(eng.sub)[1]),function(i){
  row.df <- eng.sub[i,]
  sub <- filter(sub.df,chr==row.df$CHR,frag.start<=row.df$POS,frag.end>=row.df$POS)
  ifelse(dim(sub)[1]!=0,TRUE,FALSE)
}) %>% as.logical(.)
eng.sub$probe.type <- map(1:(dim(eng.sub)[1]),function(i){
  row.df <- eng.sub[i,]
  val <- filter(sub.df,chr==row.df$CHR,frag.start<=row.df$POS,frag.end>=row.df$POS)$probe.type
  ifelse(length(val)>0,val,NA)
}) %>% as.character(.)


```



```{r}

dim(t2d.full)[1] # 159 SNPs prioritized in total for T2D
t2d.full$capture %>% sum(.) # 120 can be captured by DpnII fragments 
table(t2d.full$probe.type) # 86 can be captured by paired and 34 by single probes

dim(t2d.sub)[1] # 139 SNPs prioritized in total for T2D
t2d.sub$capture %>% sum(.) # 120 can be captured by DpnII fragments (all)
table(t2d.sub$probe.type) # 86 can be captured by paired and 34 by single probes (same as above)

```


```{r}

dim(eng.full)[1] # 16 SNPs prioritized in total for FG
eng.full$capture %>% sum(.) # 13 can be captured by DpnII fragments 
table(eng.full$probe.type) # 6 can be captured by paired and 7 by single probes

dim(eng.sub)[1] # 13 SNPs prioritized in total for FG
eng.sub$capture %>% sum(.) # 13 can be captured by DpnII fragments (all)
table(eng.sub$probe.type) # 6 can be captured by paired and 7 by single probes (same as above)

```


# Total 

```{r}

sub1a <- dplyr::select(t2d.full,one_of("CHR","POS","capture","probe.type"))
sub1b <- dplyr::select(eng.full,one_of("CHR","POS","capture","probe.type"))
sub1 <- rbind(sub1a,sub1b) # 175 total with duplicates
sub1 <- sub1[!duplicated(sub1),] # 167 unique SNPs (8 SNPs were present in both sets)
sub1$capture %>% sum(.) # 128 of 167 can be captured 
sub1$probe.type %>% table(.) # 91 by paired and 37 by single probes 



sub2a <- dplyr::select(t2d.sub,one_of("CHR","POS","capture","probe.type"))
sub2b <- dplyr::select(eng.sub,one_of("CHR","POS","capture","probe.type"))
sub2 <- rbind(sub2a,sub2b) # 152 total with duplicates
sub2 <- sub2[!duplicated(sub2),] # 147 unique SNPs (5 SNPs were present in both sets)
sub2$capture %>% sum(.) # 128 of 147 can be captured by DpnII fragment probes  
sub2$probe.type %>% table(.) # 91 by paired and 37 by single probes 

# 152 total with duplicates
# 147 unique SNPs (5 SNPs were present in both sets)
# 128 of 152 can be captured by DpnII fragment probes
# 91 by paried and 37 by single probes


```


# Checking with all SNPs of interest from First Round 

```{r}

work.dir2 <- serv.dir2 %&% "projects/wtsa/enhancer_driven/first_round/fgwas_probe_design/first_round/output_files/"

firstsnps.full <- fread(work.dir2%&%"All_SNPs_of_interest.csv") 
firstsnps.df <- fread(work.dir2%&%"All_SNPs_of_interest.csv") %>% select(.,one_of("Chrom","Start","End"))
firstsnps.df <- firstsnps.df[!duplicated(firstsnps.df),]
firstfrag.df <- fread(work.dir2%&%"Pruned_oligo_probeset.csv") %>% select(.,one_of("fragment"))
firstfrag.df$chr <- map(firstfrag.df$fragment,function(s){
  strsplit(s,split=":")[[1]][1]
}) %>% as.character(.)
firstfrag.df$frag.start <- map(firstfrag.df$fragment,function(s){
  (strsplit(s,split=":")[[1]][2] %>% strsplit(.,split="-"))[[1]][1]
}) %>% as.integer(.)
firstfrag.df$frag.end <- map(firstfrag.df$fragment,function(s){
  (strsplit(s,split=":")[[1]][2] %>% strsplit(.,split="-"))[[1]][2]
}) %>% as.integer(.)

firstfrag.gr <- GRanges(seqnames=firstfrag.df$chr,
                        IRanges(firstfrag.df$frag.start,firstfrag.df$frag.end)) %>% unique(.)
firstsnps.gr <- GRanges(seqnames=firstsnps.df$Chrom,
                        IRanges(firstsnps.df$Start,firstsnps.df$End)) %>% unique(.)
secondfrag.gr <- GRanges(seqnames=sub.df$chr,
                        IRanges(sub.df$frag.start,sub.df$frag.end)) %>% unique(.)
secondsnps.gr <- GRanges(seqnames=sub1$CHR,
                        IRanges(sub1$POS,sub1$POS)) %>% unique(.) %>% unique(.)

firstsnps.gr %over% firstfrag.gr %>% sum(.) # 222/283 first round SNPs captured by first round fragments
firstsnps.gr %over% secondfrag.gr %>% sum(.) # 7/283 first round SNPs captured by second round fragments
overlap.first <- firstsnps.gr[firstsnps.gr %over% secondfrag.gr] %>% as.data.frame(.)
overlap.first$id <- map(1:dim(overlap.first)[1],function(i){
  row.df <- overlap.first[i,]
  filter(firstsnps.full,Chrom==row.df$seqnames,Start==row.df$start)$ID %>% paste0(.,collapse=",")
}) %>% as.character(.) # These 7 SNPs correspond to these first round loci ADCY5, GNPDA2, GNPDA2, RREB1, DGKB, DCAF, GPSM1

secondsnps.gr %over% secondfrag.gr %>% sum(.) # 128/167 second round SNPs captured by second round fragments
secondsnps.gr %over% firstfrag.gr %>% sum(.) # 24/167 second round SNPs captured by first round fragments
overlap.second <- secondsnps.gr[secondsnps.gr %over% firstfrag.gr] %>% as.data.frame(.)
s1 <- t2d.full %>% select(.,one_of("Locus.ID","symbol","CHR","POS"))
s2 <- eng.full %>% select(.,one_of("Locus.ID","symbol","CHR","POS"))
sfull <- rbind(s1,s2)
sfull <- sfull[!duplicated(sfull),]

overlap.second$id <- map(1:dim(overlap.second)[1],function(i){
  row.df <- overlap.second[i,]
  filter(sfull,CHR==row.df$seqnames,POS==row.df$start)$symbol %>% unique(.) %>% paste0(.,collapse=",")
}) %>% as.character(.) # These 24 SNPs correspond to these first round loci 
# [1] "BCL11A"       "ADCY5"        "LPP"          "GNPDA2"       "GNPDA2"       "GNPDA2"       "ZBED3"     
#[8] "DGKB"         "GCK,GCK_1st"  "TP53INP1"     "UBAP2"        "ZMIZ1"        "TCF7L2"       "KCNQ1"     
#[15] "KCNQ1"        "KCNQ1"        "MAP3K11"      "MAP3K11"      "CCND1"        "CENTD2-ARAP1" "MTNR1B"    
#[22] "FBRSL1"       "FBRSL1"       "FBRSL1"


firstfrag.gr %over% secondfrag.gr %>% sum(.) # 7/191 fragments overlap from first to second round 
secondfrag.gr %over% firstfrag.gr %>% sum(.) # 7/128 fragments overlap from second to first round 

```


