---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup 

```{r}

"%&%" <- function(a,b) paste0(a,b)
library("data.table")
library("tidyverse")
library("ggbio")
library("RColorBrewer")
library("viridis")
library(Homo.sapiens)

serv.dir1 <- "/Users/jtorres/FUSE5/" #"/home/jason/science/servers/FUSE5/"
serv.dir2 <- "/Users/jtorres/FUSE2/" #"/home/jason/science/servers/FUSE2/"
got2d.dir <- "/Users/jtorres/FUSE/" #"/home/jason/science/servers/FUSE/" 
source(serv.dir1 %&% "projects/wtsa/software/peakC_functions/R/reading_functions.R")
source(serv.dir1 %&% "projects/wtsa/software/peakC_functions/R/util_functions.R")
bg.dir <- serv.dir2 %&%
  "wtsa/promoter_driven/PromCap_cis_analysis/2_unionBedgraphs/B_normalised_counts/"
winfile.dir <- serv.dir2 %&% 
  "wtsa/promoter_driven/PromCap_cis_analysis/4_plotting/C_windowed/"
parameters.file <- serv.dir2 %&% "wtsa/promoter_driven/capture_compare_parameters.txt" 
param.df <- fread(parameters.file)
#gencred.df <- fread(serv.dir1 %&% "datasets/diamante_hrc/gencred.txt")
dpn.file <- got2d.dir %&% "reference/DpnII/hg19_DpnII-sites.bed.gz"
dpn.df <- fread("cat " %&% dpn.file %&% " | zmore")


```


```{r}

prepare_input_list <- function(bg.df,vp,region.size=1e6,keep.cols=c(4,5,6)){
  flank = region.size/2
  sub <- filter(bg.df,V2>=(vp-flank),V3<=(vp+flank))
  
  # Note in union bedgraph, columns 4,5,6 correspond to Endos whereas 7,8,9 are hESC
  sub <- sub[,c(2,keep.cols)]
  df1 <- sub[,c(1,2)]; df2 <- sub[,c(1,3)]; df3 <- sub[,c(1,4)]
  names(df1) <- c("frag_pos","frag_score");names(df2) <- c("frag_pos","frag_score");
  names(df3) <- c("frag_pos","frag_score")
  l <- list(df1,df2,df3)
  return(l)
}

mean_mat <- function(bg.df,vp,region.size=1e6,keep.cols=c(4,5,6)){
  # take union bedgraph and get mean signal per fragment 
  # Note in union bedgraph, columns 4,5,6 correspond to Endos whereas 7,8,9 are hESC
  flank = region.size/2
  sub <- filter(bg.df,V2>=(vp-flank),V3<=(vp+flank))
  sub <- sub[,c(2,keep.cols)] 
  vec <- c()
  #pb <- txtProgressBar(min=0,max=dim(sub)[1],style=3)
  for (i in 1:dim(sub)[1]){
    #setTxtProgressBar(pb,i)
    val <- sub[i,c(2:4)] %>% as.numeric(.) %>% mean(.)
    vec <- append(vec,val)
  }
  m <- cbind(sub[,1],vec) %>% as.matrix(.)
  colnames(m) <- c("frag_pos","frag_sig")
  return(m)
}

```


Comparative test functions (from an earlier version of PeakC)

```{r}

runmean.perm <- function ( x1, x2, k = 21, iter = 1000 ){
  X <- matrix(NA, ncol=iter, nrow=length(x1)-k+1)
  for(i in 1:iter){
    #randomly select a value from one of the two experiments
    X[,i] <- running(ifelse(runif(length(x1)) > 0.5, x1, x2), k)
  }
  return(X)
}

running <- function(x,n=20){
  cumsum(x)->sum.v
  sum.v<-c(0,sum.v)
  #(sum.v[(n+1):length(x)]-sum.v[1:(length(x)-n)])/n
  diff(sum.v,n)/n
}

compare.data <- function( x1, x2, wSize = 21, cut.off = 0.997, abs.cut.off = 500, vp.pos = 0, vp.dist=0){
  #check whether x1 and x2 contain the same fragments
  #if not select the overlapping fragments
  x1 <- x1[x1[,1]%in%x2[,1],]
  x2 <- x2[x2[,1]%in%x1[,1],]
  
  shuffle.profile <- runmean.perm(x1[,2], x2[,2], k = wSize)
  #this is written somewhat counter-intuitively:
  #if shuffle profile is higher than the running mean of x2 in more then
  #cut.off fraction of the cases, this mean that x1 is up
  #and vice versa
  #up.i <- which(apply(shuffle.profile > running(x2[,2],wSize), 1, mean) > cut.off)
  #down.i <- which(apply(shuffle.profile < running(x2[,2],wSize), 1, mean) > cut.off)
  #alternative less counter-intuitive way
  up.i   <- which(apply(running(x1[,2],wSize) > shuffle.profile, 1, mean) > cut.off | apply(running(x2[,2],wSize) < shuffle.profile, 1, mean) > cut.off)
  down.i <- which(apply(running(x2[,2],wSize) > shuffle.profile, 1, mean) > cut.off | apply(running(x1[,2],wSize) < shuffle.profile, 1, mean) > cut.off)
  x1.run <- running(x1[,2],wSize)
  x2.run <- running(x2[,2],wSize)
  diff.x <- abs(x1.run[up.i] - x2.run[up.i])
  up.i <- up.i[diff.x > abs.cut.off]
  diff.x <- abs(x1.run[down.i] - x2.run[down.i])
  down.i <- down.i[diff.x > abs.cut.off]
  
  up.pos <- rem(x1[,1],wSize)[up.i]
  down.pos <- rem(x1[,1],wSize)[down.i]
  if(vp.dist > 0){
    up.pos <- up.pos[up.pos < vp.pos-vp.dist | up.pos > vp.pos + vp.dist]
    down.pos <- down.pos[down.pos < vp.pos-vp.dist | down.pos > vp.pos + vp.dist]
  }
  if(length(up.pos) > 0){
    up <- data.frame(pos=up.pos, col=1)
  }else{
    up <- data.frame()
  }
  if(length(down.pos) > 0){
    down <- data.frame(pos=down.pos, col=2)
  }else{
    down <- data.frame()
  }
  rbind(up, down)
}
```


```{r}

run_peakC <- function(bg.df,vp,region.size=1e6,winsize=11,fdr=0.05,abscutoff=100){
  # first list object is list of modeled results, 
  # second list object is a data frame from comparative analysis
  l1 <- prepare_input_list(bg.df,vp,region.size,keep.cols=c(4,5,6)) # Endos 
  m1 <- mean_mat(bg.df,vp,region.size,keep.cols=c(4,5,6))
  l2 <- prepare_input_list(bg.df,vp,region.size,keep.cols=c(7,8,9)) # hESC
  m2 <- mean_mat(bg.df,vp,region.size,keep.cols=c(7,8,9))
  results.modeled <- combined.analysis(data=l1,num.exp=3,vp.pos=vp,wSize=winsize,alphaFDR=fdr)#PeakC modeled 
  results.compared <- compare.data(x1=m1,# EndoC
                                    x2=m2, # hESC 
                                    wSize=winsize, vp.pos=vp, abs.cut.off=abscutoff)  # PeakC comparative
  return(list(results.modeled,results.compared))
}


prepare_plot_list <- function(id){
  data.file <- winfile.dir %&% id %&% "_window.tab"
  data <- as.tibble(read.table(data.file, header=T))
  parameters <- as.tibble(read.table(parameters.file))
  names(parameters) <- c("Viewpoint", "Chr", "Frag_start", "Frag_stop", "Exclusion_Start", 
                         "Exclusion_Stop", "Plot_Region_Start",
                         "Plot_Region_Stop", "Bin_Size", "Window_size")
  # Modify and select from parameters file =======================================
  # select viewpoint from parameters file
  viewp <- parameters %>% filter(Viewpoint == id)
  # select exclusion fragments within plotting region
  parameters <- parameters %>%
  filter(Frag_stop >= viewp$Plot_Region_Start & Frag_start <= viewp$Plot_Region_Stop)
  # add window size to exclusion zone only for viewpoint
  parameters <- parameters %>%
    mutate(Exclusion_Start = if_else(Viewpoint == id, (Exclusion_Start - Window_size),
                                     Exclusion_Start)) %>%
  mutate(Exclusion_Stop = if_else(Viewpoint == id, (Exclusion_Stop + Window_size),
                                  Exclusion_Stop))


  
  to.exclude <- parameters %>% filter(Viewpoint == id)
  # Gather Data =================================================================
  # 1 gather in long format
  d <- data %>% gather(key, value, -c(BinNum, Chr, Start, Stop))
  # 2 extract condition and replicate
  d <- d %>% 
    mutate(condition = sub('_.+', "", key, perl=T)) %>%
    mutate(replicate = sub('.+_', "", key, perl=T)) %>%
    mutate(pos = Start + (Stop - Start)/2)
  # Calculate Mean and STDEV ====================================================
  d <- d %>%
    group_by(BinNum, Chr, Start, Stop, pos, condition) %>%
  summarize(mean = mean(value), sd = sd(value)) %>%
  ungroup()  
  return(list(d,to.exclude,parameters))
}


```


```{r}

library(GenomicRanges)

get_peakc_df <- function(id){
  vec <- strsplit(id,split="__")[[1]] 
  chrom <- filter(param.df,V1==id)$V2 #(vec[grepl(x=vec,pattern="chr")] %>% strsplit(.,split="_"))[[1]][1]
  plt.list <- prepare_plot_list(id)
  plt.list[[3]] <- plt.list[[3]][grepl(id,plt.list[[3]]$Viewpoint),]
  bdg.df <- fread(bg.dir %&% id %&% "_normalised.unionbdg") %>% as.data.frame(.)
  vp = plt.list[[3]]$Frag_start
  peakc.res <- run_peakC(bdg.df,vp,region.size = 1e6,winsize=11,abscutoff = 100)
  pstart <- peakc.res[[1]]$peak
  if (length(pstart)==0){
    out.df <- data.frame(bait=NA,chrom=NA,peak.start=NA,peak.end=NA,width=NA)
    names(out.df) <- c("bait","chrom","peak.start","peak.end","width")
  } else{
    pstop <- map(pstart,function(pos){
      filter(dpn.df,V1==chrom,V2==pos-1)$V3 + 3 # offset by 3 
    }) %>% as.integer(.)
    temp.df <- data.frame(bait.id = id, chr=chrom, frag.start=pstart, frag.stop=pstop,stringsAsFactors = F)
    temp.gr <- GRanges(seqnames=temp.df$chr,IRanges(start=temp.df$frag.start,end=temp.df$frag.stop))
    temp.gr <- GenomicRanges::reduce(temp.gr)
    out.df <- data.frame(bait.id=id,as.data.frame(temp.gr),stringsAsFactors = F)
    out.df$seqnames <- out.df$seqnames %>% as.character(.)
    out.df$strand <- out.df$strand %>% as.character(.)
    out.df <- dplyr::select(out.df,-one_of("strand"))
    names(out.df) <- c("bait","chrom","peak.start","peak.end","width")    
  }
  return(out.df)
}


build_interact_df <- function(){
  file.vec <- list.files(bg.dir)
  id.vec <- map(file.vec,function(f){
    strsplit(f,split = "_normalised.unionbdg")[[1]][1]
  }) %>% as.character(.)
  exclude.vec <- c()
  id.vec <- id.vec[!(id.vec %in% exclude.vec)]
  length(id.vec)
  out.df <- c()
  pb <- txtProgressBar(min=0,max=length(id.vec),style=3)
  for (i in 1:length(id.vec)){
  #for (i in 150:length(id.vec)){ # testing 
    print(i)
    id <- id.vec[i]
    setTxtProgressBar(pb,i)
    build.df <- get_peakc_df(id)
    out.df <- rbind(out.df,build.df)
  }
  return(out.df)
}


```


```{r}



inter.df <- build_interact_df()

out.dir <- serv.dir1 %&% "projects/wtsa/promoter_driven/statistical_analyses/output_files/"
write.table(x=inter.df,file=out.dir %&% "peakC-interactions-default.txt",sep="\t",quote=F,row.names=F)

```


# Build full direcotry 



```{r}


build_results_df <- function(){
  sig.caps <- param.df$V1[param.df$V1 %in% inter.df$bait] # 162 captures with significant interactions 
  out.df <- c()
  for (cap in sig.caps){
    bait.df <- filter(param.df,V1==cap) %>% dplyr::select(.,one_of("V1","V2","V3","V4"))
    names(bait.df) <- c("variant","chrom","start","end")
    bait.df$width <- bait.df$end-bait.df$start
    bait.df$type <- "bait"
    int.df <- filter(inter.df,bait==cap)
    names(int.df) <- c("variant","chrom","start","end","width")
    int.df$type <- "interaction"
    build.df <- rbind(bait.df,int.df)
    out.df <- rbind(out.df,build.df)
  }  
  return(out.df)
}


```


```{r}

res.df <- build_results_df()
write.table(x=res.df,file=out.dir %&% "peakC-interactions-default_withBaits.txt",sep="\t",quote=F,row.names=F)

```

