---
title: "compile-peaky-interactions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup 

```{r}
"%&%" <- function(a,b) paste0(a,b)
library("data.table")
library("tidyverse")
library("GenomicRanges")
local.dir <- "/Users/jasont/science/projects/wtsa/joint_analyses/01_interaction-mapping/"
rescomp.dir <- "/Users/jasont/science/servers/FUSE5/"
cbrg.dir <- "/Users/jasont/science/servers/FUSE2/"
peaky.dir <- rescomp.dir %&% "projects/wtsa/joint_analyses/01_interaction-mapping/peaky_interactions/"
```

Capture Compare directories/files 

```{r}
# promoter capture files 
prom.dir <- cbrg.dir %&% "ddownes/04_Collaborations/" %&%
  "27_Anna_Gloyn_T2D/00_Promoter_centric_design/"
prom.cc.file  <- prom.dir %&% "03_CapComp_run/Parameters_T2D_Promoter.txt"
prom.cc.dir  <- prom.dir %&% "03_CapComp_run/T2D_Promoter_cis_analysis/"

# enhancer capture first round  
e1.dir <- cbrg.dir %&% "ddownes/04_Collaborations/" %&%
  "27_Anna_Gloyn_T2D/01_Enhancer_centric_design_FGWAS/"
e1.cc.file  <- e1.dir %&% "03_CapComp_run/" %&%
  "XXXXXXX.txt" # NOT READY YET 
e1.cc.dir  <- e1.dir %&% "03_CapComp_run/XXXXXX/" # NOT READY YET 

# enhancer capture second round  
e2.dir <- cbrg.dir %&% "ddownes/04_Collaborations/" %&%
  "27_Anna_Gloyn_T2D/02_Enhancer_centric_design_credible_sets/"
e2.cc.file  <- e2.dir %&% "03_CapComp_run/" %&%
  "Parameters_T2D_Credible.txt"
e2.cc.dir  <- e2.dir %&% "03_CapComp_run/T2D_Credible_cis_analysis/"
```

Read hg19 dpnII fragment file 

```{r}
dpn.df <- fread(prom.cc.dir %&% "6_PeakyInputs/hg19_dpnII_Fragments_key.bed",
                header=TRUE)
```

## Functions for creating interaction output files 

```{r}
# DD used 0.01 as cutoff for rjmcmc_pos significance value 
extract_sig_interactions <- function(cc.df,peaky.file,rjmcmc.pos,
                                     experiment="promoter",
                                     celltype="Endo"){
  pky.df <- fread(peaky.file)
  sig.df <- filter(pky.df,rjmcmc_pos >= rjmcmc.pos) %>% 
    dplyr::select(one_of("baitID","preyID","dist","N","rjmcmc_pos"))
  if (dim(sig.df)[1]>0){
    bait.id <- sig.df$baitID %>% unique(.)
    bait.df <- filter(dpn.df,ID==bait.id)
    cap.df <- filter(cc.df,V2=="chr"%&%bait.df$chrom,
                V3==bait.df$chromStart-2)
    capture <- cap.df$V1
    seqnames <- cap.df$V2
    vp <- cap.df$V3 %>% as.integer()
    out.df <- c()
    for (i in 1:dim(sig.df)[1]){
      #print(i)
      row.df <- sig.df[i,]
      prey.id <- row.df$preyID
      prey.df <- filter(dpn.df,ID==prey.id)
      start <- prey.df$chromStart -2; end <- prey.df$chromEnd + 2
      width <- abs(end-start)
      v <- c(start,end)
      dist.from.vp.abs <- min(abs(v-vp))
      type <- ifelse(dist.from.vp.abs <= 2.5e+05,"proximal","distal")
      sign.val <- unique(sign(v-vp))
      if (length(sign.val)==1){
        dist.from.vp <- unique(sign(v-vp)) * dist.from.vp.abs
      } else{
        dist.from.vp <- c(v-vp)[grepl(v-vp,pattern=dist.from.vp.abs)]
      }
      n <- row.df$N
      rjmcmc_pos <- row.df$rjmcmc_pos
      build.df <- data.frame("experiment"=experiment,"celltype"=celltype,
                             "capture"=capture,"seqnames"=seqnames,
                             "start"=start,"end"=end,"width"=width,"type"=type,
                             "dist.from.vp"=dist.from.vp,"N"=n,
                             "rjmcmc_pos"=rjmcmc_pos,stringsAsFactors = F)
      out.df <- rbind(out.df,build.df)
    }
    return(out.df)    
  } else{
    return(NULL)
  }
}

merge_interactions <- function(sig.df){
  experiment <- sig.df$experiment %>% unique(.)
  celltype <- sig.df$celltype %>% unique(.)
  capture <- sig.df$capture %>% unique(.)
  seqnames <- sig.df$seqnames %>% unique(.)
  sub.df <- dplyr::select(sig.df,one_of("seqnames","start","end"))
  sub.df$start.expand1K <- sub.df$start - 1000
  sub.df$end.expand1K <- sub.df$end + 1000
  sub.gr <- GRanges(seqnames=sub.df$seqnames,
                    IRanges(start=sub.df$start,end=sub.df$end))
  sub.expand.gr <- GRanges(seqnames=sub.df$seqnames,
                IRanges(start=sub.df$start.expand1K,end=sub.df$end.expand1K))
  red.gr <- reduce(sub.gr);red.expand.gr <- reduce(sub.expand.gr)
  out.df1 <- as.data.frame(red.gr); out.df2 <- as.data.frame(red.expand.gr)
  out.df1 <- data.frame("experiment"=experiment,"celltype"=celltype,
                        "capture"=capture,"seqnames"=seqnames,
                        "start"=out.df1$start,"end"=out.df1$end,
                        "width"=out.df1$width,stringsAsFactors = F)
  out.df2 <- data.frame("experiment"=experiment,"celltype"=celltype,
                        "capture"=capture,"seqnames"=seqnames,
                        "start"=out.df2$start,"end"=out.df2$end,
                        "width"=out.df2$width,stringsAsFactors = F)
  return(list(out.df1,out.df2))
}

get_dist_from_vp <- function(int.df,cc.df){
  #pb <- txtProgressBar(min=0,max=dim(int.df)[1],style=3)
  dist.from.vp <- map(1:dim(int.df)[1],function(i){
    #setTxtProgressBar(pb,i)
    #print(i)
    row.df <- int.df[i,]
    vp <- filter(cc.df,V1==row.df$capture)$V3 %>% as.integer(.)
    v <- c(row.df$start,row.df$end)
    val <- min(abs(v - vp))
    sign.val <- unique(sign(v-vp))
    if (length(sign.val)==1){
      unique(sign(v-vp)) * val
    } else{
      c(v-vp)[grepl(v-vp,pattern=val)]
    }
  }) %>% as.integer(.)
  int.df$dist.from.vp <- dist.from.vp
  return(int.df)
}

```


```{r}

consolidate_experiment_results <- function(cc.file,peaky.file.dir,rjmcmc.pos,
                                           exper="promoter"){
  #cc.df <- fread(cc.file,fill=TRUE,sep="\t",sep2=" ",header=FALSE)
  cc.df <- read.table(file=cc.file,header=FALSE)
  peaky.file.vec <- list.files(peaky.file.dir) #c("promoter-capture.856876.peaky-output.txt")#
  out.df0 <- c()
  out.df1 <- c()
  out.df2 <- c() 
  #pb <- txtProgressBar(min=0,max=length(peaky.file.vec))
  for (i in 1:length(peaky.file.vec)){
    #setTxtProgressBar(pb,i)
    print(i)
    peaky.file <- peaky.file.dir %&% peaky.file.vec[i]
    print(peaky.file)
    sig.df <- extract_sig_interactions(cc.df,peaky.file,rjmcmc.pos,experiment=exper,
                                        celltype="Endo")
    if (is.null(sig.df)==FALSE){
      merge.list <- merge_interactions(sig.df)
      sig.df1 <- merge.list[[1]] %>% get_dist_from_vp(.,cc.df)
      sig.df1$type <- ifelse(abs(sig.df1$dist.from.vp) <= 2.5e+05,"proximal","distal")
      sig.df2 <- merge.list[[2]] %>% get_dist_from_vp(.,cc.df)
      sig.df2$type <- ifelse(abs(sig.df2$dist.from.vp) <= 2.5e+05,"proximal","distal")
      out.df0 <- rbind(out.df0,sig.df)
      out.df1 <- rbind(out.df1,sig.df1)
      out.df2 <- rbind(out.df2,sig.df2)      
    } else{
      print("No significant interactions for file: " %&% peaky.file.vec[i])
    }
  }
  return(list(out.df0,out.df1,out.df2))
}

```

## Promoter-capture

rjmcmc.pos threshold >= 0.01
```{r}
prom.list <- consolidate_experiment_results(prom.cc.file,
                                            peaky.dir %&% "promoter-capture/",
                                            rjmcmc.pos=0.01)
write.table(x=prom.list[[1]],file=peaky.dir%&%
  "promoter_endo_peaky-interactions_unmerged-full-info_rjmcmc-pos01.txt",
            sep="\t",quote=F,row.names=F)

write.table(x=prom.list[[2]],file=peaky.dir%&%
  "promoter_endo_peaky-interactions_rjmcmc-pos01.txt",
            sep="\t",quote=F,row.names=F)

write.table(x=prom.list[[3]],file=peaky.dir%&%
  "promoter_endo_peaky-interactions_merge1K_rjmcmc-pos01.txt",
            sep="\t",quote=F,row.names=F)
```

rjmcmc.pos threshold >= 0.05
```{r}
prom.list <- consolidate_experiment_results(prom.cc.file,
                                            peaky.dir %&% "promoter-capture/",
                                            rjmcmc.pos=0.05)
write.table(x=prom.list[[1]],file=peaky.dir%&%
  "promoter_endo_peaky-interactions_unmerged-full-info_rjmcmc-pos05.txt",
            sep="\t",quote=F,row.names=F)

write.table(x=prom.list[[2]],file=peaky.dir%&%
  "promoter_endo_peaky-interactions_rjmcmc-pos05.txt",
            sep="\t",quote=F,row.names=F)

write.table(x=prom.list[[3]],file=peaky.dir%&%
  "promoter_endo_peaky-interactions_merge1K_rjmcmc-pos05.txt",
            sep="\t",quote=F,row.names=F)
```

rjmcmc.pos threshold >= 0.10
```{r}
prom.list <- consolidate_experiment_results(prom.cc.file,
                                            peaky.dir %&% "promoter-capture/",
                                            rjmcmc.pos=0.10)
write.table(x=prom.list[[1]],file=peaky.dir%&%
  "promoter_endo_peaky-interactions_unmerged-full-info_rjmcmc-pos10.txt",
            sep="\t",quote=F,row.names=F)

write.table(x=prom.list[[2]],file=peaky.dir%&%
  "promoter_endo_peaky-interactions_rjmcmc-pos10.txt",
            sep="\t",quote=F,row.names=F)

write.table(x=prom.list[[3]],file=peaky.dir%&%
  "promoter_endo_peaky-interactions_merge1K_rjmcmc-pos10.txt",
            sep="\t",quote=F,row.names=F)
```


## Enhancer 2nd Round capture 

```{r}
e2.list <- consolidate_experiment_results(e2.cc.file,
                                        peaky.dir %&% "enhancer2nd-capture/",
                                        exper="enhancer2nd")
write.table(x=e2.list[[1]],file=peaky.dir%&%
            "enhancer2nd_endo_peaky-interactions_unmerged-full-info.txt",
            sep="\t",quote=F,row.names=F)
write.table(x=e2.list[[2]],file=peaky.dir%&%
            "enhancer2nd_endo_peaky-interactions.txt",
            sep="\t",quote=F,row.names=F)
write.table(x=e2.list[[3]],file=peaky.dir%&%
            "enhancer2nd_endo_peaky-interactions_merge1K.txt",
            sep="\t",quote=F,row.names=F)
```



