---
title: "Capture Summaries"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup 

```{r}

"%&%" <- function(a,b) paste0(a,b)

library("data.table")
library("tidyverse")
library("viridis")
library("grid");library("gridExtra")

cbrg.serv <- "/home/jason/science/servers/FUSE2/"
rescomp.serv <- "/home/jason/science/servers/FUSE5/"
input.dir.enhan <- cbrg.serv %&% "wtsa/enhancer_driven/first_round/capture_compare_cis_analysis/1_reports/"
input.dir.prom <- cbrg.serv %&% "wtsa/promoter_driven/PromCap_cis_analysis/1_reports/"
plot.dir <- rescomp.serv %&% "projects/wtsa/enhancer_driven/first_round/statistical_anlayses/plots/"

```

# Functions 

```{r}

build_input_df <- function(input.dir,input.vec){
  out.df <- c()
  for (s in input.vec){
    fname <- input.dir %&% s %&% "_cisReport.txt"
    build.df <- fread(fname)
    build.df$Sample <- s
    out.df <- rbind(out.df,build.df)
  }
  return(out.df)
}


total.count.plot <- function(df,yscale="1M",
                             input.vec=c("Endo_A","Endo_B","Endo_C","hESC_A","hESC_B","hESC_C")){
  v1 <- c()
  v2 <- c()
  for (s in input.vec){
    val1 <- filter(df,Sample==s)$Total %>% sum(.)
    val2 <- filter(df,Sample==s)$Cis %>% sum(.)
    v1 <- append(v1,val1); v2 <- append(v2,val2)
  }
  plot.df <- data.frame(Sample=input.vec,Total.Count=v1,Cis.Count=v2)
  if (yscale=="1M"){
    plot.df$Total.Count <- plot.df$Total.Count/1000000
    plot.df$Cis.Count <- plot.df$Cis.Count/1000000    
  } else{
    plot.df$Total.Count <- plot.df$Total.Count/100000
    plot.df$Cis.Count <- plot.df$Cis.Count/100000
  }
  plot.df$Sample <- factor(plot.df$Sample,levels=input.vec)
  plt <- ggplot(data=plot.df,aes(x=Sample,y=Total.Count)) + 
    geom_bar(stat="identity",color="black",fill=viridis(10)[8]) + 
    geom_bar(stat="identity",aes(x=Sample,y=Cis.Count),color="black",fill=viridis(10)[3]) + 
    geom_text(size=3,aes(x=Sample,y=Cis.Count+0.2,label=prettyNum(Cis.Count,digits=3))) + 
    geom_text(size=3,aes(x=Sample,y=Cis.Count-0.2,label="(" %&% prettyNum(Cis.Count/Total.Count,digits=2) %&% ")")) + 
    geom_text(size=3,aes(x=Sample,y=Total.Count+0.2,label=prettyNum(Total.Count,digits=3))) + 
    theme_bw() 
  
  if (yscale=="1M"){
    plt = plt + ylab("Interaction Counts (Million)") +
      scale_y_continuous(breaks=1:10) 
  } else{
    plt = plt + ylab("Interaction Counts (100K)") +
      scale_y_continuous(breaks=1:15) 
  }
  plt
}


cis.hist.v1 <- function(df,enh=TRUE){
  if (enh==TRUE){
    df$CellType <- map(df$Sample,function(s){
    strsplit(x=s,split="_")[[1]][1]
    }) %>% as.character(.)
  } else{
    df$CellType <- map(df$Sample,function(s){
      substr(s,1,4)
      }) %>% as.character(.) 
  }
  plt <- ggplot(data=df,aes(x=Cis/1000)) +
    geom_histogram(color=viridis(10)[6],
                   fill=viridis(10)[8]) + 
    geom_vline(xintercept=25,color=viridis(10)[1]) +
    facet_wrap(~CellType) + 
    scale_x_continuous(breaks=seq(0,100,20)) + 
    ylab("Count") + xlab("Cis Interactions (thousands)")
}

cis.hist.v2 <- function(df){
  #plot.df$Sample <- factor(df$Sample,levels=input.vec)
  plt <- ggplot(data=df,aes(x=Cis/1000)) +
    geom_histogram(color=viridis(10)[6],
                   fill=viridis(10)[8]) + 
    geom_vline(xintercept=25,color=viridis(10)[1]) +
    facet_wrap(~Sample) + 
    scale_x_continuous(breaks=seq(0,100,20)) + 
    ylab("Count") + xlab("Cis Interactions (thousands)")
}


cis.table.v1 <- function(df,enh=TRUE){
  if (enh==TRUE){
    df$CellType <- map(df$Sample,function(s){
    strsplit(x=s,split="_")[[1]][1]
    }) %>% as.character(.)
  } else{
    df$CellType <- map(df$Sample,function(s){
      substr(s,1,4)
      }) %>% as.character(.) 
  }
  sub1 <- df %>% group_by(CellType) %>%
    summarise_at(vars("Cis"),
              list(Mean=mean,Q1=quantile,
                   Median=median),
              probs=0.25) %>% as.data.frame(.)
  sub2 <- df %>% group_by(CellType) %>%
    summarise_at(vars("Cis"),
              list(Q3=quantile,Max=max),
              probs=0.75) %>% as.data.frame(.)
  tab.df <- inner_join(sub1,sub2,by='CellType')
  return(tab.df)
}


cis.table.v2 <- function(df){
  sub1 <- df %>% group_by(Sample) %>%
    summarise_at(vars("Cis"),
              list(Mean=mean,Q1=quantile,
                   Median=median),
              probs=0.25) %>% as.data.frame(.)
  sub2 <- df %>% group_by(Sample) %>%
    summarise_at(vars("Cis"),
              list(Q3=quantile,Max=max),
              probs=0.75) %>% as.data.frame(.)
  tab.df <- inner_join(sub1,sub2,by='Sample')
  percGreater25K <- map(tab.df$Sample,function(s){
    sub <- filter(df,Sample==s)
    (sum(sub$Cis > 25000) / length(sub$Cis))
  }) %>% as.numeric(.) %>% prettyNum(.,digits=3)
  percGreater10K <- map(tab.df$Sample,function(s){
    sub <- filter(df,Sample==s)
    (sum(sub$Cis > 10000) / length(sub$Cis))
  }) %>% as.numeric(.) %>% prettyNum(.,digits=3)
  tab.df$'>10K (%)' <- percGreater10K
  tab.df$'>25K (%)'<- percGreater25K
  return(tab.df)
}

```


# Enhancer (First Round Experiment)

```{r}
 
enh.df <- build_input_df(input.dir=input.dir.enhan,
                     input.vec=c("Endo_A","Endo_B","Endo_C",
                                 "hESC_A","hESC_B","hESC_C"))
tot.plt <- total.count.plot(enh.df,yscale="1M",input.vec=c("Endo_A","Endo_B","Endo_C","hESC_A","hESC_B","hESC_C"))
ggsave(plot=tot.plt,filename=plot.dir%&%"summary_counts_enh1st.png",width=5,height=5)
ggsave(plot=tot.plt,filename=plot.dir%&%"summary_counts_enh1st.pdf",width=5,height=5)

cishist.plt1 <- cis.hist.v1(enh.df)
ggsave(plot=cishist.plt1,filename=plot.dir%&%"hist_enh1st.png",
       width=6,height=3)
ggsave(plot=cishist.plt1,filename=plot.dir%&%"hist_enh1st.pdf",
       width=6,height=3)

cistab1 <- tableGrob(cis.table.v1(enh.df))
ggsave(plot=cistab1,filename=plot.dir%&%"table_enh1st.png",
       width=5,height=1)
ggsave(plot=cistab1,filename=plot.dir%&%"table_enh1st.pdf",
       width=5,height=1)

cishist.plt2 <- cis.hist.v2(enh.df)
ggsave(plot=cishist.plt2,filename=plot.dir%&%"histAll_enh1st.png",
       width=9,height=6)
ggsave(plot=cishist.plt2,filename=plot.dir%&%"histAll_enh1st.pdf",
       width=9,height=6)

cistab2 <- tableGrob(cis.table.v2(enh.df))
ggsave(plot=cistab2,filename=plot.dir%&%"tableAll_enh1st.png",
       width=6.5,height=2.5)
ggsave(plot=cistab2,filename=plot.dir%&%"tableAll_enh1st.pdf",
       width=6.5,height=2.5)

```

# Promoter Capture 

```{r}

prom.df <- build_input_df(input.dir=input.dir.prom,
                     input.vec=c("EndoBA","EndoBC","EndoBD",
                                 "BlymphA","BlymphB","BlymphC"))
tot.plt <- total.count.plot(prom.df,yscale="10K",
                            input.vec=c("EndoBA","EndoBC","EndoBD",
                                 "BlymphA","BlymphB","BlymphC"))
ggsave(plot=tot.plt,filename=plot.dir%&%"summary_counts_prom.png",width=5,height=5)
ggsave(plot=tot.plt,filename=plot.dir%&%"summary_counts_prom.pdf",width=5,height=5)

cishist.plt1 <- cis.hist.v1(prom.df,enh=FALSE)
ggsave(plot=cishist.plt1,filename=plot.dir%&%"hist_prom.png",
       width=5,height=3)
ggsave(plot=cishist.plt1,filename=plot.dir%&%"hist_prom.pdf",
       width=5,height=3)

cistab1 <- tableGrob(cis.table.v1(prom.df,enh=FALSE))
ggsave(plot=cistab1,filename=plot.dir%&%"table_prom.png",
       width=5,height=1)
ggsave(plot=cistab1,filename=plot.dir%&%"table_prom.pdf",
       width=5,height=1)

cishist.plt2 <- cis.hist.v2(prom.df)
ggsave(plot=cishist.plt2,filename=plot.dir%&%"histAll_prom.png",
       width=9,height=6)
ggsave(plot=cishist.plt2,filename=plot.dir%&%"histAll_prom.pdf",
       width=9,height=6)

cistab2 <- tableGrob(cis.table.v2(prom.df))
ggsave(plot=cistab2,filename=plot.dir%&%"tableAll_prom.png",
       width=6.5,height=2.5)
ggsave(plot=cistab2,filename=plot.dir%&%"tableAll_prom.pdf",
       width=6.5,height=2.5)


```

