---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup 


```{r}

"%&%" <- function(a,b) paste0(a,b)
library("data.table")
library("tidyverse")
library("ggbio")
library("RColorBrewer")
library("viridis")
library("Homo.sapiens")

serv.dir1 <- "/home/jason/science/servers/FUSE5/"
serv.dir2 <- "/home/jason/science/servers/FUSE2/"
got2d.dir <- "/home/jason/science/servers/FUSE/" 
cbrg.dir.prom <- serv.dir2 %&% "wtsa/promoter_driven/" 
cbrg.dir.enh <- serv.dir2 %&% "wtsa/enhancer_driven/first_round/" 
rescomp.dir.prom <- serv.dir1 %&%
  "projects/wtsa/promoter_driven/statistical_analysis/output_files/"
rescomp.dir.enh <- serv.dir1 %&%
  "projects/wtsa/enhancer_driven/first_round/statistical_anlayses/output_files/"
param.file.prom <- cbrg.dir.prom %&% "capture_compare_parameters.txt"
param.file.enh <- cbrg.dir.enh %&% "capture_compare_parameters_pruned_chr.txt"

data(genesymbol, package = "biovizBase")


```


```{r}


science_theme <- theme(
  panel.grid.major = element_line(size = 0.5, color = "grey"),
  panel.grid.minor = element_blank(),
  plot.title = element_text(hjust = 0.5),
  text = element_text(size = 14),  axis.line = element_line(color="black", size = 0.7),
  axis.line.x = element_line(color="black", size = 0.7),
  axis.line.y = element_line(color="black", size = 0.7),
  # plot.margin = unit(c(0.7,0.7,0.7,0.7), "lines"),
  panel.border=element_blank(),
  strip.background = element_blank()
)

```


# Plotting Functions 

```{r}

prepare_plot_list <- function(id,experiment="promoter"){
  # Experiment can either be "promoter" or "enhancer"
  if (experiment=="promoter"){
    winfile.dir <- cbrg.dir.prom %&% "PromCap_cis_analysis/4_plotting/C_windowed/"
    parameters.file <- param.file.prom
  } else if (experiment=="enhancer"){
    winfile.dir <- cbrg.dir.enh %&% "capture_compare_cis_analysis/4_plotting/C_windowed/"
    parameters.file <- param.file.enh
  } else{
    print("Experiment can either be 'promoter' or 'enhancer'")
  }
  data.file <- winfile.dir %&% id %&% "_window.tab"
  data <- as.tibble(read.table(data.file, header=T))
  parameters <- as.tibble(read.table(parameters.file))
  names(parameters) <- c("Viewpoint", "Chr", "Frag_start", "Frag_stop", "Exclusion_Start",
                         "Exclusion_Stop", "Plot_Region_Start",
                         "Plot_Region_Stop", "Bin_Size", "Window_size")  
  # select viewpoint from parameters file
  viewp <- parameters %>% filter(Viewpoint == id)
  # select exclusion fragments within plotting region
  parameters <- parameters %>%
  filter(Frag_stop >= viewp$Plot_Region_Start & Frag_start <= viewp$Plot_Region_Stop)
  # add window size to exclusion zone only for viewpoint
  parameters <- parameters %>%
    mutate(Exclusion_Start = if_else(Viewpoint == id, (Exclusion_Start - Window_size),
                                     Exclusion_Start)) %>%
  mutate(Exclusion_Stop = if_else(Viewpoint == id, (Exclusion_Stop + Window_size),
                                  Exclusion_Stop))
  to.exclude <- parameters %>% filter(Viewpoint == id)
  # Gather Data =================================================================
  # 1 gather in long format
  d <- data %>% gather(key, value, -c(BinNum, Chr, Start, Stop))
  # 2 extract condition and replicate
  d <- d %>% 
    mutate(condition = sub('_.+', "", key, perl=T)) %>%
    mutate(replicate = sub('.+_', "", key, perl=T)) %>%
    mutate(pos = Start + (Stop - Start)/2)
  # Calculate Mean and STDEV ====================================================
  d <- d %>%
    group_by(BinNum, Chr, Start, Stop, pos, condition) %>%
  summarize(mean = mean(value), sd = sd(value)) %>%
  ungroup()  
  return(list(d,to.exclude,parameters))
}

```


```{r}

capc_plot <- function(id,experiment,plotwin=5e5,plotmax=NULL){
  plt.list <- prepare_plot_list(id,experiment)
  plt.list[[3]] <- plt.list[[3]][grepl(id,plt.list[[3]]$Viewpoint),]
  vp = plt.list[[3]]$Frag_start
  d <- plt.list[[1]]; to.exclude <- plt.list[[2]]; 
  params <- plt.list[[3]]
  if (experiment=="promoter"){
    d$condition <- factor(d$condition,levels=c("EndoB","Blymph"))
    bg.dir <- cbrg.dir.prom %&%
      "PromCap_cis_analysis/2_unionBedgraphs/B_normalised_counts/"
    peakc.mod.df <- rescomp.dir.prom %&% 
      "peakC-modeled-default_EndoC.txt" %>% fread(.)
    peakc.comp.df <- rescomp.dir.prom %&% 
      "peakC-comparative-default.txt" %>% fread(.)
  } else if(experiment=="enhancer"){
    d$condition <- factor(d$condition,levels=c("Endo","hESC"))
    bg.dir <- cbrg.dir.enh %&%
      "capture_compare_cis_analysis/2_unionBedgraphs/B_normalised_counts/"
    peakc.mod.df <- rescomp.dir.enh %&% 
      "peakC-modeled-default_EndoC.txt" %>% fread(.)
    peakc.comp.df <- rescomp.dir.enh %&% 
      "peakC-comparative-default.txt" %>% fread(.)
  } else{
    print("Experiment can either be 'promoter' or 'enhancer'")
  }

  bdg.df <- fread(bg.dir %&% id %&% "_normalised.unionbdg") %>% as.data.frame(.)
  
  if (is.null(plotmax)==TRUE){
    plotmax <- filter(d,Stop<to.exclude$Exclusion_Start |
                      Start>to.exclude$Exclusion_Stop)$mean %>% 
                      max(.) %>% mean(.) %>% round(.)
    plotmax <- plotmax+50    
  }


  p <- ggplot(filter(d,Stop<to.exclude$Exclusion_Start |
                      Start>to.exclude$Exclusion_Stop),
              aes(x=pos, y=mean, col = condition, fill = condition)) +
    geom_ribbon(inherit.aes = F, 
                aes(x=pos, ymin=mean-sd, ymax=mean+sd, fill=condition), alpha=.35) + 
    geom_line() + 
    scale_fill_manual(values=viridis(20)[c(3,9)],name="Cell Type") +
    scale_color_manual(values=viridis(20)[c(3,9)],name="Cell Type") +
    geom_rect(data=to.exclude, inherit.aes=F, 
              aes(xmin=Exclusion_Start, xmax=Exclusion_Stop), 
              ymin=-25, ymax=max(d$mean)+max(d$sd), col="lightgrey", fill="white") + 
    geom_rect(data=params, inherit.aes=F, 
              aes(xmin=Frag_start, xmax=Frag_stop), ymin=-25, 
              ymax=max(d$mean)+max(d$sd), col="grey", fill="grey") + 
    labs(x="Genomic Position", y="Mean Interaction") + 
    ggtitle(id) +
    theme_bw() + science_theme +  
    theme(panel.grid = element_blank())	 
  
  peakc.mod <- peakc.mod.df$peak.start #peakc.res[[1]]$peak
  peakc.comp <- peakc.comp.df$peak.start #peakc.res[[1]]$peak
  
  peakc.df <- filter(bdg.df,V2 %in% peakc.mod) %>% 
    dplyr::select(.,one_of("V1","V2","V3")) %>% 
    filter(.,V3<to.exclude$Exclusion_Start |
                      V3>to.exclude$Exclusion_Stop)
  comp.df <- filter(bdg.df,V2 %in% peakc.comp) %>% 
    dplyr::select(.,one_of("V1","V2","V3")) %>% 
    filter(.,V3<to.exclude$Exclusion_Start |
                      V3>to.exclude$Exclusion_Stop)
  if (dim(peakc.df)[1]>0){
    p = p + geom_rect(data=peakc.df,inherit.aes=F,aes(xmin=V2,xmax=V3),
                ymin=-(plotmax/50),ymax=(plotmax/50),size=0.1,
                color="firebrick3",fill="firebrick1")
  }
  if (dim(comp.df)[1]>0){
    p = p + geom_rect(data=comp.df,inherit.aes=F,aes(xmin=V2,xmax=V3),
                ymin=-(plotmax/50),ymax=(plotmax/50),size=0.1,
                color=viridis(20)[20],fill=viridis(20)[15])    
  }
  p <- p + coord_cartesian(xlim=c(params$Frag_start-(plotwin), 
                           params$Frag_stop+(plotwin)),
                  ylim=c(0,plotmax)) 
  return(p)
}

```




```{r}

gene_plot <- function(id,experiment,plotwin=5e5){
  plt.list <- prepare_plot_list(id,experiment)
  plt.list[[3]] <- plt.list[[3]][grepl(id,plt.list[[3]]$Viewpoint),]
  params <- plt.list[[3]]
  reg.gr <- GRanges(seqnames=params$Chr,
                 IRanges(params$Frag_start-(plotwin/2),
                 params$Frag_stop+(plotwin/2)))
  wh <- genesymbol[genesymbol %over% reg.gr] 
  wh <- range(wh, ignore.strand = TRUE)
  p <- autoplot(Homo.sapiens, which = wh,
                color=cividis(20)[1],
                fill=cividis(20)[4]) 
  p = p + theme_bw() + 
    theme(panel.grid=element_blank()) +
    ylab("Transcripts") + 
    xlab("Genomic Position")
  return(p)
}

```



# Testing plotting functions, looks good 

```{r}

plt1 <- capc_plot(id="ADCY5",experiment="promoter",plotwin=5e5)
plt2 <- capc_plot(id="ADCY5__1TG__te__chr3_123054770",
                  experiment="enhancer",plotwin=5e5)
gplt <- gene_plot(id="ADCY5",experiment="promoter",plotwin=5e5)

plt <- tracks(plt1,plt2,gplt) + 
  scale_x_sequnit(unit="Mb") + 
  ylim(0,200)


```




