---
title: "01.1_Prepare-CredbileSet-T2D-file.Rmd"
author: "Jason Torres"
date: "February 15, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Setup libraries and directories 

```{r}
"%&%" <- function(a,b) paste0(a,b) 
library("dplyr")
library("data.table")
library("ggplot2")

serv.dir <- "/Users/jtorres/FUSE/"
rds.dir <- serv.dir %&% "projects/wtsa/enhancer_driven/probe_design/rds/"
fgwas.dir <- serv.dir %&% "projects/wtsa/enhancer_driven/probe_design/fgwas_output/"

fgwas.input.file <- serv.dir %&% "projects/t2d-integration/fgwas/" %&% 
  "credsets_diagram_1KG/fgwas_input/fgwas_input27.txt.gz"

```


Will take as input credible sets from the DIAGRAM (imputed to 1K Genomes) fine-mapping study. Will compare probe designs from these input files: 
  * original file from Anubha
  * fGWAS fine-mapping file (generated from my T2D-Integration pipeline) 

```{r}

cred.df <- fread("cat " %&% fgwas.input.file %&% " | zmore") %>% dplyr::select(one_of("SNPID","CHR","POS","SEGNUMBER","PPA"))

fgwas.outfile <- fgwas.dir %&% "diagram_gwasmod.bfs.gz"

fgwas.df <- fread("cat " %&% fgwas.outfile %&% " | zmore") %>% dplyr::select(one_of("id","PPA","chunk"))
names(fgwas.df) <- c("SNPID","PPA.fgwas","SEGNUMBER")
fgwas.df$SEGNUMBER <- fgwas.df$SEGNUMBER + 1 # fgwas file is 0-based 

cred.df <- inner_join(cred.df,fgwas.df,by="SNPID")
cred.df <- cred.df[(cred.df$SEGNUMBER.x == cred.df$SEGNUMBER.y),]
cred.df <- mutate(cred.df, change=PPA.fgwas-PPA) %>% arrange(desc(change))
cred.df <- dplyr::select(cred.df, -SEGNUMBER.y)
names(cred.df)[which(names(cred.df)=="SEGNUMBER.x")] = "SEGNUMBER"

```

Append Locus information 

```{r}
gwas.dir <- serv.dir%&%"reference/gwas/diagram_1Kgenomes/"
gwas.dir <- gwas.dir %&% "DIAGRAM_T2D_GWAS_1000G_99_Credsets_Unpublished_2017/"
locindex.file <- gwas.dir %&% "list.of.96.loci.used.for.finemapping.txt"
li.df <- fread(locindex.file,header=FALSE);names(li.df) <- c("SNPID","LOCUS")
lookup.dir <- serv.dir%&%"projects/t2d-integration/fGWAS_files/diagram_1Kgenomes/"
lookup.df <- readRDS(lookup.dir %&% "diagram_1KGenomes_fGWAS-core.v2.df.RDS")

pb <- txtProgressBar(min = 0, max = dim(cred.df)[1], initial = 0, style = 3)
LOCUS <- as.character(sapply(1:length(cred.df$SNPID), function(i){
  setTxtProgressBar(pb, i)
  s <- cred.df$SNPID[i]
  lead <- filter(lookup.df,SNPID==s)$LEADSNP
  s <- gsub("chr","",lead)
  if (length(s) > 1){
    vec <- unique(as.character(sapply(1:length(s), function(e){
      loc <- filter(li.df,SNPID==s[e])$LOCUS
      loc <- gsub(" #","",loc)
      return(loc)
    })))
    loc <- paste(vec,collapse=" & ")
  } else{
    loc <- filter(li.df,SNPID==s)$LOCUS
  }
  if (length(loc) == 0) loc <- NA 
  loc <- gsub(" #","",loc)
  if (length(loc) >1) loc <- loc[1]
  return(loc)
}))

cred.df <- cbind(cred.df,LOCUS)
cred.df$LOCUS <- as.character(cred.df$LOCUS)
saveRDS(cred.df,file=rds.dir%&%"fgwas.cred.diag.df.RDS")

```


