---
title: "peaky development"
output: html_notebook
---

# Setup 

```{r}

"%&%" <- function(a,b) paste0(a,b)
library("data.table")
library("tidyverse")
library("peaky")

serv.dir1 <- "/home/jason/science/servers/FUSE5/"
serv.dir2 <- "/home/jason/science/servers/FUSE2/"
got2d.dir <- "/home/jason/science/servers/FUSE/" 

work.dir <- serv.dir1 %&% "projects/wtsa/enhancer_driven/first_round/statistical_anlayses/"
write.dir <- work.dir  %&% "peaky_analyses/analysis_files/"

cc.dir <- serv.dir2 %&% "wtsa/enhancer_driven/first_round/"
peaky.input.dir <- cc.dir %&% "capture_compare_cis_analysis/6_PeakyInputs/"

#  hESC_counts.tsv  
parameters.file <- cc.dir %&% "capture_compare_parameters_pruned_chr.txt" 

```



Read Peaky input files (outputted from Capture Compare script)

```{r}

param.df <- fread(parameters.file)
pkyinter.df <- fread(peaky.input.dir %&% "Endo_counts.tsv") # Just running on Endos for now 
pkyfrag.df <- fread(peaky.input.dir %&% "hg19_DpnII_Fragments_key.bed")

```


Map Capture IDs to Bait Ids for interpreting downstream results 

```{r}

lookup_bait_id <- function(capid){
  # capid <- "PTGFRN__4DF__uc__chr1_117453383"
  row.df <- filter(param.df,V1==capid)
  c <- row.df$V2 %>% gsub("chr","",.)
  start.pos <- row.df$V3 + 2 
  end.pos <- row.df$V4 - 2
  filter(pkyfrag.df,chrom==c,chromStart==start.pos | chromEnd==end.pos)$ID 
}

map_cap_to_baitid <- function(){
  out.df <- c()
  pb <- txtProgressBar(min=0,max=dim(param.df)[1],style=3)
  for (i in 1:dim(param.df)[1]){
    setTxtProgressBar(pb,i)
    capid <- param.df$V1[i]
    baitid <- lookup_bait_id(capid)
    build.df <- data.frame(capture.id=capid,bait.id=baitid,stringsAsFactors = F)
    out.df <- rbind(out.df,build.df)
  }
  return(out.df)
}


```


```{r}

idmap.df <- map_cap_to_baitid()
write.table(x=idmap.df,file = write.dir %&% "capture-bait-id-map.txt",sep="\t",quote=F,row.names=F)

```


# Peaky 

## Initial normalization of counts


```{r}

BI = bin_interactions(pkyinter.df, pkyfrag.df, bins=5)
print(BI$bins)

```


```{r}

models = by(BI$interactions, BI$interactions$dist.bin, model_bin, subsample_size=1000)
plot(models[[1]]$fit)

residuals = lapply(models, "[[", "residuals")
bins = split(BI$interactions, BI$interactions$dist.bin)
BTS = split_baits(bins, residuals)
saveRDS(object = BTS,file=write.dir%&%"BTS.RDS")


```


```{r}

relevant_bait = BTS[baitID==301716] # first capture bait 
zoom = relevant_bait[abs(relevant_bait$dist)<1e6]
plot(x=zoom$dist, 
     y=zoom$residual, 
     xlab="Distance from bait (bp)", 
     ylab="Adjusted readcount",
     main=paste("Bait",unique(zoom$baitID)))
peak_center = zoom$dist[which.max(zoom$residual)]
zoom$distance_from_peak = abs(zoom$dist-peak_center)
single_peak = zoom[distance_from_peak<4e5,]
#Define the distance function and find the best fit for omega
dist_exp = function(offset, strength, omega_power){
  omega = 10^omega_power
  strength * exp(-(abs(offset * omega)))
}
fit_omega = nls(residual~dist_exp(distance_from_peak,strength,omega_power), 
    data=single_peak, 
    start=list(strength=5, omega_power=-3.8))
{
plot(single_peak$distance_from_peak, single_peak$residual, 
     main=paste0("Decay of signal for an isolated peak\nEstimate of omega = 10^",
                round(coefficients(fit_omega)["omega_power"],3)),
     xlab="Distance from center of peak (bp)",
     ylab="Adjusted readcount")
lines(single_peak$distance_from_peak, fitted.values(fit_omega), col="red", lwd=3)
}
```


## Determine appropriate Omega value for joint analysis of neighboring fragments 

Will manually inspect some baits 


```{r}

get_omega <- function(baitid){
  relevant_bait = BTS[baitID==baitid]
  zoom = relevant_bait[abs(relevant_bait$dist)<1e6]
  peak_center = zoom$dist[which.max(zoom$residual)]
  zoom$distance_from_peak = abs(zoom$dist-peak_center)
  single_peak = zoom[distance_from_peak<4e5,]
  #Define the distance function and find the best fit for omega
  dist_exp = function(offset, strength, omega_power){
    omega = 10^omega_power
    strength * exp(-(abs(offset * omega)))
  }
  fit_omega = nls(residual~dist_exp(distance_from_peak,strength,omega_power), 
      data=single_peak, 
      start=list(strength=5, omega_power=-3.8))  
  return(as.numeric(coefficients(fit_omega)[2]))
}

pick_omega <- function(){
  idmap.df <- as.data.frame(idmap.df)
  baitchecks <- idmap.df[!duplicated(idmap.df$capture.id),]$bait.id %>% sample(.,size=10,replace=FALSE)
  vec <- c()
  for (bait in baitchecks){
    if (bait %in% BTS$baitID){
      v <- get_omega(bait)
      vec <- append(vec,v)
    }
  }
  return(mean(vec))
}


```


```{r}

set.seed(1)
omega.to.use <- pick_omega() # -4.305031
saveRDS(object = omega_to_use,file=write.dir%&%"omega.to.use.RDS")

```

