---
title: "01.2_Prepare-CredbileSet-T2D-Metabo-file.Rmd"
author: "Jason Torres"
date: "March 15, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Setup libraries and directories 

```{r}
"%&%" <- function(a,b) paste0(a,b) 
library("dplyr")
library("data.table")
library("ggplot2")

serv.dir <- "/Users/jtorres/FUSE/"
rds.dir <- serv.dir %&% "projects/wtsa/enhancer_driven/probe_design/rds/"

fgwas.dir <- serv.dir %&% "projects/wtsa/enhancer_driven/probe_design/fgwas_output/"

fgwas.input.file <- serv.dir %&% "projects/t2d-integration/fgwas/" %&% "credsets_metabochip/intermediate_files/metabo-fgwas-core.txt"

```



```{r}

cred.df <- fread(fgwas.input.file) %>% dplyr::select(one_of("SNPID","CHR","POS","SEGNUMBER","PPA","LOCUS"))

fgwas.outfile <- fgwas.dir  %&% "metabochip_gwasmod.bfs.gz"
fgwas.df <- fread("cat " %&% fgwas.outfile %&% " | zmore") %>% dplyr::select(one_of("id","PPA","chunk"))
names(fgwas.df) <- c("SNPID","PPA.fgwas","SEGNUMBER")
fgwas.df$SEGNUMBER <- fgwas.df$SEGNUMBER + 1 # fgwas file is 0-based 

cred.df <- inner_join(cred.df,fgwas.df,by="SNPID")
cred.df <- cred.df[(cred.df$SEGNUMBER.x == cred.df$SEGNUMBER.y),]
cred.df <- mutate(cred.df, change=PPA.fgwas-PPA) %>% arrange(desc(change))
cred.df <- dplyr::select(cred.df, -SEGNUMBER.y)
names(cred.df)[which(names(cred.df)=="SEGNUMBER.x")] = "SEGNUMBER"

saveRDS(cred.df,file=rds.dir%&%"fgwas.cred.metab.df.RDS")

```



