---
title: "Untitled"
author: "Jason Torres"
date: "February 15, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Note: This data was generated by Anthony. It contains gene-level eQTL results from xxx Oxford islet samples. 
I had previously subetted the full data file to only significant eQTLs (FDR < 0.05). The significant set are used here. 


```{r}
"%&%" <- function(a,b) paste0(a,b) 
library("data.table")
library("dplyr")
library("EnsDb.Hsapiens.v75")

serv.dir <- "/Users/jtorres/FUSE/"
rds.dir <- serv.dir %&% "projects/wtsa/enhancer_driven/probe_design/rds/"

```


Islet eQTLs 

```{r}

eqtl.file <- serv.dir%&%"reference/islet/eqtls/from_anthony/top_variant_per_gene-BH.txt.gz"
key.file <- serv.dir%&%"reference/islet/eqtls/from_anthony/top_variant_per_gene-BH-keyfile.txt.gz"

#eqtl.file <- serv.dir%&%"reference/islet/eqtls/from_anthony/fdr05_cis_eQTL_genelevel.txt.gz"
#key.file <- serv.dir%&%"reference/islet/eqtls/from_anthony/snp_keyfile.txt.gz"

e.df <- fread("cat " %&% eqtl.file %&% " | zmore")
key.df <- fread("cat " %&% key.file %&% " | zmore")
key.df$POS <- gsub("29683808_G/A","29683808",key.df$POS)
key.df$POS <- as.integer(key.df$POS)
names(e.df) <- c("RSID","ENSID","Beta","T","P","Q")
e.df <- inner_join(e.df,key.df,by="RSID")
e.df <- e.df[!duplicated(e.df),]
#source("https://bioconductor.org/biocLite.R")
#biocLite("EnsDb.Hsapiens.v75")
ensref.df <- data.frame(genes(EnsDb.Hsapiens.v75)$gene_id,
                        genes(EnsDb.Hsapiens.v75)$gene_name,
                        stringsAsFactors = FALSE)
names(ensref.df) <- c("ENSID","GENE")

ensid2gene <- function(){
  pb <- txtProgressBar(min = 0, max = dim(e.df)[1], initial = 0, style = 3)
  GENE <- as.character(sapply(1:length(e.df$ENSID), function(i){
    setTxtProgressBar(pb, i) 
    e <- e.df$ENSID[i]
    name <- strsplit(x=e,split=".",fixed=TRUE)[[1]][1]
    gene <- filter(ensref.df,ENSID==name)$GENE
    return(gene)
  }))
  close(pb)
  return(GENE)
}

GENE <- ensid2gene()
e.df <- cbind(e.df,GENE); e.df$GENE <- as.character(e.df$GENE)

SNPID <- as.character(sapply(1:length(e.df$CHR),function(i){
  s <- paste(e.df$CHR[i],e.df$POS[i],sep=":")
  return(s)
}))
e.df <- cbind(e.df,SNPID)  
e.df$SNPID <- as.character(e.df$SNPID)
eqtl.df <- e.df 
saveRDS(eqtl.df,file=rds.dir%&%"eqtl.df.RDS")

```

