---
title: "Build EndoC-BH1 ATAC-seq peak data frame"
author: "Jason Torres"
date: "February 15, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
"%&%" <- function(a,b) paste0(a,b) 
library("data.table")
library("dplyr")

serv.dir <- "/home/jason/science/servers/FUSE/" #"/Users/jtorres/FUSE/"
work.dir <- serv.dir %&% "projects/wtsa/enhancer_driven/fgwas_probe_design/first_round/"
rds.dir <- work.dir %&% "RDS/"


```


EndoC-BH1 ATAC-seq annotations

```{r}

atac.path1 <- serv.dir %&% "projects/wtsa_archive/wtsa/EndoC-BH1_ATAC/call_peaks/mac2_all_reads/"
atac.path1 <- atac.path1 %&% "endoB_bio1_tech1_atac_peaks.narrowPeak"
atac.path2 <- serv.dir %&%"reference/EndoCBH1/EndoC_chromatin_Parker/atacSeq/"
atac.path2 <- atac.path2 %&% "endoC_50.broadPeak.fdr0.05.noBlacklist.bed.gz"

a.df1 <- fread(atac.path1)
a1.df <- dplyr::select(a.df1,one_of("V1","V2","V3"))
names(a1.df)<-c("chr","start","end")
id <- rep("Oxford",dim(a1.df)[1])
a1.df$id <- id
#a1.gr <- gread(a1.df)

a.df2 <- fread("cat " %&% atac.path2 %&% " | zcat")
a2.df <- dplyr::select(a.df2,one_of("V1","V2","V3"))
names(a2.df)<-c("chr","start","end")
id <- rep("Parker",dim(a2.df)[1])
a2.df$id <- id
#a2.gr <- gread(a2.df)

atac.df <- rbind(a1.df,a2.df)
saveRDS(atac.df,file=rds.dir %&% "atac.df.RDS")

```


